packer/http/centos-6.6/ks.cfg

In the CentOS 6.6 distribution SELinux is set to "enforcing" instead of "permissive" regardless of the fact that `ks.cfg` contains the line `selinux --permissive`.
This line is ignored by anaconda and the resulted box has the following SELinux configuration:
```bash
$  sestatus
SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   enforcing
Mode from config file:          enforcing
Policy version:                 24
Policy from config file:        targeted
$ cat /etc/selinux/config
SELINUX=enforcing
SELINUXTYPE=targeted
```
I've noticed that it is reproduced only on **centos-6.6**. If we build "centos-7.0" box, or even try to reset to 99cacf4 and build "centos-6.5" box, then there will be SELinux in the permissive mode.
Seems like …

centos-6.6: Force to set SELinux to a permissive mode

---

packer/http/centos-5.11/ks.cfg
packer/http/centos-6.6/ks.cfg
packer/http/centos-7.0/ks.cfg
packer/http/fedora-20/ks.cfg
packer/http/fedora-21/ks.cfg
packer/scripts/fedora/ks.cfg

This addresses both concerns of #318 and #325. We were downloading the
SSL CA bundle over http because at the point in time when we wanted to
even do that we might not have been in a state where the SSL
certificates from curl.haxx.se could be verified. Using http is just
as good at that point as using SSL without verification. However...
This addresses the concern raised in #325, whereby the upstream
cacert.pem removed certificates used by services such as AWS S3,
causing SSL connections to those sites to fail to verify. We should
rely on the ca-bundle.crt that comes with the openssl package on the
platforms in question (centos/fedora).

Fixes #325, #318 - don't download cacert.pem

---

packer/scripts/centos/cleanup.sh

Before I had an issue using the box with a static ip for NFS sharing in
vagrant, resulting in
```
ERROR: [/etc/sysconfig/network-scripts/ifdown-eth] Device ens33 has MAC
address 00:0C:29:F8:96:74, instead of configured address
00:0C:29:59:C4:97. Ignoring.
```
While the cleanup script already fixed this for `eth0`, CentOS7 seems to
have changed the device naming, therefor it's also needed for `ens33`.
Instead of removing the text of the entries, I opted for deleting the
whole line as there's no need for empty lines in the ifcfg-file.

Fix mac address issue for ens33 on centos 7

---

MAINTAINERS.md

Add MAINTAINERS.md file.

---

README.md

The current README points to basebox, which has been deprecated. This updates to point to Boxcutter, which is under active development.

update README to point to Boxcutter intead of basebox

---

.gitignore
bin/bento

This is a first-step addition of a small binary wrapper around Packer to
help inject custom variables, inject metadata and re-normalize the
templates using `packer fix`.
In its present implementation, no external RubyGems are required in an
attempt to maximize portability between platforms.

Add packer/bin/bento for building templates.

---

.travis.yml
Gemfile

The following are updates to the Travis builds:
* Upgrade to Packer 0.7.5
* Upgrade to Ruby 2.2.x
* Ensure that the new container-based system is used
* Remove Vagrant Bundler dependencies from Gemfile

TravisCI project updates

---

README.md

Update README with Ubuntu 15.04 boxes.

---

bin/bento

Don't write metadata file in `bento build` dry run mode.

---

macosx-10.10.json
scripts/macosx/minimize.sh
scripts/macosx/networking.sh
scripts/macosx/vmtools.sh
vagrantfile_templates/macosx.rb

This is a rebase-and-squash of #353.
Closes #353

Add Mac OS X 10.10 template.

---

bin/bento

The build metadata produced by `bin/bento` is modified to contain
Vagrant provider-compatible metadata as in the following example:
{
"name": "chef/debian-8.0",
"version": "2.0.20150702012417",
"build_timestamp": "20150702012417",
"git_revision": "9c7e4544c57fd9da497eda416fb7486cf941d6d7_dirty",
"box_basename": "chef__debian-8.0-2.0.20150702012417.git.9c7e4544c57fd9da497eda416fb7486cf941d6d7_dirty",
"template": "debian-8.0-amd64",
"providers": [
{
"name": "parallels",
"file": "chef__debian-8.0-2.0.20150702012417.git.9c7e4544c57fd9da497eda416fb7486cf941d6d7_dirty.parallels.box",
"checksum_type": "sha256",
"checksum": "5ce86c9c31edadf69500b1c680be3d2afa88d1def2c972c82a066cc482855d41"
},
{
"name": "virtualbox",
"file": "chef__debian-8.0-2.0.20150702012417.git.9c7e4544c57fd9da497eda416fb7486cf …

Add provider metadata to metdata files on build.

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json
scripts/macosx/cleanup.sh
scripts/macosx/hostname.sh
scripts/macosx/minimize.sh
scripts/macosx/networking.sh
scripts/macosx/update.sh
scripts/macosx/vagrant.sh

The following improvements are made in this commit:
* Using the `template` user variable to replace repetition of
`"macosx-10.*"` style strings throughout
* Bump the minimum version of Packer from 0.6.0 to 0.7.0
* Supply a `HOME_DIR` environment variable for provisioner scripts to
use
* Remove the optional autologin logic, which wasn't being triggered by
default leading to less behavior "tuning knobs" in the templates
* Remove now-unused user variables `arch` and `autologin`
* Add consistent `_README` user variable to explain how to obtain and
prepare the base disk image
* Rename all template names from `"macosx-10.*"` to `"chef/macosx-10.*"`
* Extract the `iso_checksum_type` into a user variable and reference it
in the templates
* Call all provider scripts with `sh -eux` which will: (e) …

[macosx-*] Improve DRYness & correctness of Mac templates.

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json

The following environment variables will be made available to the
provisioner shell scripts if set on the workstation:
* `http_proxy`
* `https_proxy`
* `no_proxy`

[macosx-*] Add support for {http,https,no}_proxy environment variables.

---

scripts/common/metadata.sh
scripts/common/minimize.sh
scripts/common/sshd.sh
scripts/common/vmtools.sh
scripts/ubuntu/cleanup.sh
scripts/ubuntu/networking.sh
scripts/ubuntu/sudoers.sh
scripts/ubuntu/update.sh
scripts/ubuntu/vagrant.sh
ubuntu-10.04-amd64.json
ubuntu-10.04-i386.json
ubuntu-12.04-amd64.json
ubuntu-12.04-i386.json
ubuntu-14.04-amd64.json
ubuntu-14.04-i386.json
ubuntu-14.10-amd64.json
ubuntu-14.10-i386.json
ubuntu-15.04-amd64.json
ubuntu-15.04-i386.json

The following improvements are made in this commit:
* Ensure that all related provisioner shell scripts are written using
more conservative bourne coding idioms
* Call all provisioner scripts with `sh -eux` which will: (e) exit
immeditately if a command exits with a non-zero exit status, (u)
treats unset variables as an error, and (x) outputs the command and
its expanded arguments or associated word list
* Use the `template` user variable to replace repetition of
`"ubuntu-*"`style strings throughout
* Support a `HOME_DIR` environment variable for provisioner scripts to
use
* Remove now-unused user variable `arch`
* Rename all template names from `"ubuntu-*"` to `"chef/ubuntu-*"`
* Extract the `iso_checksum` and `iso_checksum_type` into user
variables and reference them in the templates
* …

[ubuntu-*] Improve DRYness, correctness, and speed of Ubuntu templates.

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json
ubuntu-10.04-amd64.json
ubuntu-10.04-i386.json
ubuntu-12.04-amd64.json
ubuntu-12.04-i386.json
ubuntu-14.04-amd64.json
ubuntu-14.04-i386.json
ubuntu-14.10-amd64.json
ubuntu-14.10-i386.json
ubuntu-15.04-amd64.json
ubuntu-15.04-i386.json

This allows the publishing namespace to be separated from the box name.

[macosx-*, ubuntu-*] Remove name prefixes from templates.

---

debian-6.0.10-amd64.json
debian-6.0.10-i386.json
debian-7.8-amd64.json
debian-7.8-i386.json
debian-8.1-amd64.json
debian-8.1-i386.json
scripts/debian/cleanup.sh
scripts/debian/networking.sh
scripts/debian/sudoers.sh
scripts/debian/update.sh

The following improvements are made in this commit:
* Ensure that all related provisioner shell scripts are written using
more conservative bourne code idioms
* Call all provisioner scripts with `sh -eux` which will (e) exit
immediately if a command exits with a non-zero exit status, (u) treats
unset variables as an error, and (x) outputs the command and its
expanded arguments or associated word list
* Use the `template` user variable to replace repetition of `"debian-*"`
style strings throughout
* Support a `HOME_DIR` environment variable for provisioner scripts to
use
* Remove now-unused user variable `arch`
* Extract the `iso_checksum` and `iso_checksum_type` values into user
variables and reference them in the templates
* Construct the `iso_url` value from the `mirror`, …

[debian-*] Improve DRYness, correctness, & speed of Debian templates.

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json

When running some tests of the Xcode and Vagrant cookbooks, I found that the virtual machines were running out of drive space before the Chef runs completed. This should buy the VMs a bit more headroom.

[macosx-*] Increase disk_size to ~40G from ~20G.

---

README.md
Rakefile

- This update heralds the new age of the bento build pipeline
- Boxes will *soon* be built for each PR / commit
- Boxes now exist on Atlas https://atlas.hashicorp.com/bento
- Boxes will also continue to be served from S3 until upcoming changes to kitchen-vagrant
- Readme is now way prettier

Update Readme and small fixes/cleanup to Rake tasks

---

vagrantfile_templates/macosx.rb

The fix was released in Vagrant 1.7.3.

Enable key insertion on OS X

---

http/centos-5.11/ks.cfg
http/centos-6.7/ks.cfg
http/centos-7.1/ks.cfg

Cosmetic fix to avoid matching and rewriting the comment:
```
```
in the `/etc/sudoers` file.

CentOS kickstarts: Change sed to not rewrite sudo comments

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json
scripts/macosx/vmtools.sh

I've added Parallels builder support for `macosx-*` templates.
Verified on Packer v0.8.6 + Parallels Desktop Pro 11.0.0
I'm ready to maintain the compatibility with Parallels Desktop, so feel free to highlight me if something is going wrong with that.

Add Parallels builder to Mac OS X templates

---

macosx-10.10.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json

This is an addition to my previous PR: GH-436
Without specifying the VM name, it will be named `packer-parallels-iso`, which is not unique.

Add "vm_name" parameter to Mac OS X templates for Parallels builder

---

README.md

This brings the instructions in the Readme in line with reality. It also includes some edits for clarity.

Updating readme to reflect reality

---

README.md

First up, thanks for bento! I've used these boxes for a while now and really appreciate the effort that goes into this project :sparkles:.
I ran into a small issue, but I think I have a solution. `vagrant up` failed when I used the `chef/` prefix in my `Vagrantfile`.
Here is the error I experienced:
```
$> vagrant --version
Vagrant 1.7.4
$> cat Vagrantfile
Vagrant.configure(2) do |config|
config.vm.box = "chef/ubuntu-12.04"
end
$> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/ubuntu-12.04' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: >= 0
==> default: Loading metadata for box 'chef/ubuntu-12.04'
default: URL: https://atlas.hashicorp.com/chef/ubuntu-12.04
The box you're adding …
```

Use bento prefix for box names in README

---

centos-5.11-i386.json
centos-5.11-x86_64.json
debian-6.0.10-amd64.json
debian-6.0.10-i386.json
ubuntu-10.04-amd64.json
ubuntu-10.04-i386.json
ubuntu-12.04-amd64.json
ubuntu-12.04-i386.json
ubuntu-14.10-amd64.json
ubuntu-14.10-i386.json

Other platforms using sha1 will update this in their upcoming respective refactor PRs

Updating platforms to use sha256

---

http/centos-5.11/ks.cfg
http/fedora-20/ks.cfg
http/fedora-21/ks.cfg
http/fedora-22/ks.cfg

auth and authconfig are the same thing, they're used twice in the kickstart
files. the first one tells authconfig to use sha512, the second one tells it to
use md5. the end result the machine is configured to use md5 instead of sha512
for password hashing
https://github.com/rhinstaller/pykickstart/blob/master/docs/kickstart-docs.rst#auth-or-authconfig

remove duplicate auth/authconfig and use sha512 algorithm for password hashing

---

.travis.yml
scripts/windows/Autounattend.xml
scripts/windows/SetupComplete.cmd
scripts/windows/nano_cleanup.ps1
scripts/windows/nano_create.ps1
scripts/windows/postunattend.xml
vagrantfile_templates/windows-nano.rb
windows-nano-tp3.json

This adds a Windows nano server box. I have running `bin/bento build windows-nano-tp3` on ubuntu 14.04 server, copied the .box file to a windows box with virtual box. Then vagrant Up'd it and it worked.

Windows Nano

---

scripts/windows/SetupComplete.cmd
vagrantfile_templates/windows-nano.rb
windows-nano-tp3.json

T be able to easily establish a powershell remoting connection to a nano box from another windows vm, I am adding a host only network to expose a reachable ip.
To be able to easily create a SMB share, I am enabling File and Printer sharing firewall rules.

Adds host only network for nano and enables file and printer sharing

---

fedora-22-i386.json
fedora-22-x86_64.json
http/fedora-22/ks.cfg
scripts/fedora/22-build-tools.sh

Fedora 22 builds are broken because apparently one cannot install GCC from kickstart (reasons unknown)
- add build tool script just for Fedora 22
- update kickstart and remove deprecated `--nobase` option
- doesn't fix i386 build but that is it's own yak

Fixing Fedora 22 build tools to fix vm tools

---

CHANGELOG.md
README.md

* Create/update Changelog
* Update Readme

Cutting 2.2.2 release

---

.gitignore
Rakefile

- More aggressive cleanup
- ignore .kitchen directory

Be more aggressive about removing "bento-*" vagrant boxes

---

scripts/common/minimize.sh

The blkid utility returns exit status 2 when the requested label can't
be found.
Fixes #420

Support swapless builders in minimize.sh

---

scripts/common/sshd.sh

Blindly appending entries to `sshd_config` is problematic if the
configuration keys are already defined and/or the configuration file is
missing a trailing newline.

attempt to manage sshd_config in an [more] idempotent manner

---

macosx-10.11.json

Project [osx-vm-templates](https://github.com/timsutton/osx-vm-templates) already supports OS X 10.11 El Capitan.
Here I've just copied the template `macosx-10.10.json` and changed the name inside.
It works fine - verified with `parallels` provider for Vagrant.

Add template for OS X 10.11 El Capitan

---

scripts/common/sshd.sh

This PR fixes the following error:
```
==> parallels-iso: Provisioning with shell script: scripts/common/sshd.sh
parallels-iso: grep: character class syntax is [[:space:]], not [:space:]
parallels-iso: grep: character class syntax is [[:space:]], not [:space:]
```
cc: @jhoblitt

Fix grep character class syntax in sshd.sh script

---

scripts/ubuntu/networking.sh

There is a typo. It should be `/var/lib/dhcp/*`, like in the similar script for Debian: https://github.com/chef/bento/blob/250efaa/scripts/debian/networking.sh#L8

Fix dhcp settings cleanup in Ubuntu 12.04 and higher

---

centos-7.2-x86_64.json
http/centos-7.2/ks.cfg
oracle-7.2-x86_64.json
rhel-7.2-x86_64.json

Updated RHEL/CentOS/OEL to **7.2**
_Note:_ To install Parallels Tools package ```selinux-policy-devel``` is needed.
All builds passes on Parallels Desktop Pro 11.1.1, VMware Fusion Pro 7.1.3, and VirtualBox 5.0.10. Beside that I haven't done much testing of the boxes.

Enterprise Linux 7.2 (RHEL/CentOS/OEL)

---

scripts/debian/cleanup.sh
scripts/ubuntu/cleanup.sh

DKMS is needed to recompile the guest additions if a new kernel
is installed.  Removing the C/C++ packages also removes the `dkms`
package.  This fixes #509 for Dedian based distros.

Stops DKMS package from being removed.

---

scripts/centos/cleanup.sh

Fix error in ```cleanup.sh``` script introduced in d01cb1d7
Declaring varibles can't have spaces surrounding the equals sign. This
only affects OEL.

Fix error in cleanup.sh script introduced in d01cb1d7

---

scripts/centos/cleanup.sh

This PR makes thec lean-up of udev rules similar to ubuntu/debian approach:
https://github.com/chef/bento/blob/6d5771a/scripts/ubuntu/networking.sh#L3-L8
https://github.com/chef/bento/blob/250efaa/scripts/debian/networking.sh#L3-L8
It's not enough just to remove `/etc/udev/rules.d/70-persistent-net.rules`. We should also replace it with a directory and remove `/lib/udev/rules.d/75-persistent-net-generator.rules` to prevent the generating of new rules. 
P.s. It is already implemented in boxcutter project and it works fine:
https://github.com/boxcutter/centos/blob/a732c24/script/cleanup.sh#L3-L14

Disable automatic udev rules for network interfaces in CentOS

---

scripts/centos/cleanup.sh
scripts/centos/networking.sh
scripts/common/minimize.sh
scripts/common/shutdown.sh
scripts/common/sshd.sh
scripts/common/vagrant.sh
scripts/common/vmtools.sh
scripts/debian/cleanup.sh
scripts/debian/update.sh
scripts/fedora/22-build-tools.sh
scripts/fedora/shutdown.sh
scripts/freebsd/update.sh
scripts/freebsd/vmtools.sh
scripts/macosx/hostname.sh
scripts/macosx/vagrant.sh
scripts/macosx/vmtools.sh
scripts/omnios/postinstall.sh
scripts/omnios/vmtools.sh
scripts/opensuse/sudoers.sh
scripts/sles/remove-dvd-source.sh
scripts/sles/sudoers.sh
scripts/sles/zypper-locks.sh
scripts/solaris/vmtools.sh
scripts/solaris10/vmtools.sh
scripts/ubuntu/cleanup.sh
scripts/ubuntu/sudoers.sh
scripts/ubuntu/update.sh
scripts/ubuntu/vagrant.sh

This change-set represent the minimum possible change to either fix or
suppress all warnings from the shellcheck linter.  The presence of these
warnings is an annoyance for those with automatic linting enabled in
their editor of choice.
This include dead variable removal but no logic or stylistic
improvements.

fix or suppress all shellcheck warnings

---

scripts/centos/cleanup.sh
scripts/centos/networking.sh
scripts/common/minimize.sh
scripts/common/shutdown.sh
scripts/common/sshd.sh
scripts/common/vagrant.sh
scripts/common/vmtools.sh
scripts/debian/cleanup.sh
scripts/debian/update.sh
scripts/fedora/22-build-tools.sh
scripts/fedora/shutdown.sh
scripts/freebsd/update.sh
scripts/freebsd/vmtools.sh
scripts/macosx/hostname.sh
scripts/macosx/vagrant.sh
scripts/macosx/vmtools.sh
scripts/omnios/postinstall.sh
scripts/omnios/vmtools.sh
scripts/opensuse/sudoers.sh
scripts/sles/remove-dvd-source.sh
scripts/sles/sudoers.sh
scripts/sles/zypper-locks.sh
scripts/solaris/vmtools.sh
scripts/solaris10/vmtools.sh
scripts/ubuntu/cleanup.sh
scripts/ubuntu/sudoers.sh
scripts/ubuntu/update.sh
scripts/ubuntu/vagrant.sh

Reverts chef/bento#494 - looks like some of the shellcheck stuff breaks builds. Notably changes to `scripts/debian/update.sh`

Revert "fix or suppress all shellcheck warnings"

---

scripts/centos/cleanup.sh

`/etc/redhat-release` is owned by packages like redhat-release-server-6Server-6.7.0.3.el6.x86_64.rpm, centos-release-7-2.1511.el7.centos.2.10.x86_64.rpm, oraclelinux-release-7.2-1.0.5.el7.x86_64.rpm, sl-release-7.1-2.sl7.x86_64.rpm and can be used for a recognition between these distros at least

simplify distro detection for RHEL-derivatives

---

macosx-10.11.json

Copied from [Tim Sutton](https://github.com/timsutton/osx-vm-templates/blob/master/packer/template.json#L63)'s template

Fix guest_os_type for VirtualBox

---

debian-8.2-amd64.json
debian-8.2-i386.json

Debian 8.2 has been moved to the "archive", so the default URL should be updated

Update mirror URL for Debian 8.2

---

CHANGELOG.md
README.md

Also cleaned up the README to use named anchors instead of numbers and broke up the 32 bit vs 64bit

Cutting 2.2.4

---

http/ubuntu-12.04/preseed.cfg
http/ubuntu-14.04/preseed.cfg
http/ubuntu-15.10/preseed.cfg
scripts/ubuntu/update.sh

Simplify and dist-upgrade for great benefit. Totally borrowed from https://github.com/boxcutter/ubuntu <3

Ubuntu: use dist-upgrade and install build packages in preseed

---

fedora-22-i386.json
fedora-22-x86_64.json
fedora-23-i386.json
fedora-23-x86_64.json
http/fedora-22/ks.cfg
http/fedora-23/ks.cfg
scripts/fedora/build-tools.sh

There's no reason to manually partition Fedora.  Let's just do the same thing we do on RHEL.  We get the same result.  Also let's remove the Fedora version from the build tools script since it impacts both 22 and 23.

Simplify swap and clarify the build tools Fedora version

---

omnios-r151014.json
omnios-r151018.json

OmniOS re-released the ISOs with fixes, but maintained the same release
numbers so the SHAs need to get updated.  These are straight from their
site and confirmed to be valid locally.

Update omnios ISO SHAs

---

ubuntu-16.04-i386.json

There is a trailing space in `iso_url` value. Being represented as %20 in URL, it causes a build error:
```
==> parallels-iso: Downloading or copying ISO
2016/04/27 21:19:10 ui:     parallels-iso: Downloading or copying: http://releases.ubuntu.com/16.04/ubuntu-16.04-server-i386.iso%20
parallels-iso: Downloading or copying: http://releases.ubuntu.com/16.04/ubuntu-16.04-server-i386.iso%20
2016/04/27 21:19:10 packer: 2016/04/27 21:19:10 Acquiring lock to download: http://releases.ubuntu.com/16.04/ubuntu-16.04-server-i386.iso%20
2016/04/27 21:19:10 packer: 2016/04/27 21:19:10 Parsed URL: &url.URL{Scheme:"http", Opaque:"", User:(*url.Userinfo)(nil), Host:"releases.ubuntu.com", Path:"/16.04/ubuntu-16.04-server-i386.iso ", RawPath:"", RawQuery:"", Fragment:""}
2016/04/27 21:19:10 packer: …
```

Fix iso_name in ubuntu-16.04-i386.json

---

fedora-23-x86_64.json

Similar to how the latest vmware and vagrant has issues related to the pci slot change, this seems to fix #521

Possible fix for Fedora 23 vmware issue

---

Rakefile

- This logic will likely move into bento binary but for now this fixes linux builders running vmware workstation.

Choose kitchen driver based on available vagrant plugins

---

Gemfile
Rakefile
bin/bento
build.sh

* take all the logic in Rakefile and migrate to bento CLI tool
* 1:1 translation at present
* plan to make test and upload take arguments
* headless now an option, not hardcode based on platform
* miscellaneous updates to support Linux builders
* remove all bento-* vagrant boxes before AND after test runs

Move all the logic out of Rakefile and into bin/bento

---

scripts/solaris/vagrant.sh
solaris-11-x86.json

Redefining home to /home/vagrant fails since that doesn't exist on
Solaris

Fix vagrant.sh failing on Solaris nodes

---

debian-7.11-amd64.json
debian-7.11-i386.json

Tested on:
- VirtualBox 5.0.14
- VMware Fusion 7.1.3
- Parallels Desktop for Mac Pro ~ 11

Updated Debian 7 to 7.11

---

http/debian-6.0/preseed.cfg
http/debian-7/preseed.cfg
http/debian-8/preseed.cfg
http/ubuntu-10.04/preseed.cfg
http/ubuntu-12.04/preseed.cfg
http/ubuntu-14.04/preseed.cfg
http/ubuntu-14.10/preseed.cfg
http/ubuntu-15.04/preseed.cfg
http/ubuntu-15.10/preseed.cfg

Currently unattended upgrades are enabled, causing unexpected behavior when the daily apt upgrade job runs (with cron.daily on sysv/upstart hosts, and at-boot plus semi-randomly twice a day on hosts with systemd).
Setting this value to none disables the upgrade jobs, in favor of package upgrades only happening when explicitly requested. This would resolve issue #609

Disable automated package upgrades on Debian-like boxes

---

debian-6.0.10-amd64.json
debian-6.0.10-i386.json
scripts/debian/debian6-apt.sh

I have added a script to set the debian6 sources to point to archive.debian.org instead of mirrors.kernel.org which is now deprecated for debian6

update apt sources to use archive.debian.org for packages

---

scripts/centos/cleanup.sh

Fixes https://github.com/chef/bento/issues/388 and https://github.com/Parallels/vagrant-parallels/issues/265
Details about the root of issue: https://github.com/Parallels/vagrant-parallels/issues/265#issuecomment-226960702
The solution has been taken from Boxcutter: https://github.com/boxcutter/centos/commit/be4174ea6e8c053d25f970d524d1801c6b21c55f
It might look not very clear, so any other solutions are welcome. The current implementation does the following (_only on RHEL/CentOS 7_):
- Cleans up the NetworkManager state and settings before the box packaging
- Appends `/etc/rc.d/rc.local` by the script, which fixes names of network devices in NM configuration
- Being executed only on the first boot, the script mentioned above removes itself from the `/etc/rc.d/rc.local`.
I've verified it …

Fix new-style device naming from Network Manager on RHEL/CentOS 7

---

.kitchen.yml.erb
bin/bento
bootstrap.sh

- Use an ERB template instead of a JSON blob which makes for prettier yaml
- added new flag `bin/bento test -p PROVISIONER` to set provisioner (defaults to shell)

The power of ERB compels you

---

opensuse-leap-42.1-x86_64.json

This seams to improve the reliability of the builds of OpenSUSE Leap 42.1 on all builders.

OpenSUSE Leap 42.1: requires 768 Mb memory.

---

macosx-10.10.json
macosx-10.11.json
macosx-10.7.json
macosx-10.8.json
macosx-10.9.json
scripts/macosx/disablesleep.sh

By default, Mac OS X will sleep after a certain time period. This isn't optimal for Vagrant boxes as you can't SSH to the box when it is sleeping. This change disables sleep at box creation.

Add script to disable system sleep for Mac OS X

---

http/ubuntu-12.04/preseed.cfg
http/ubuntu-14.04/preseed.cfg
http/ubuntu-15.10/preseed.cfg

The Ubuntu 14.04 config was using tasksel to add the "ubuntu-server" task, which doesn't exist. Maybe it used to. The "server" task is actually what we want, and pulls in packages for a headless setup, such
as tmux.
The "ubuntu-server" task was essentially a no-op, so it didn't break anything, but it did cause a lot of packages to be omitted. See [full comparison here](https://gist.github.com/conorsch/7123209a86a2c577ba465b80cb05b0ef).
Closes #653.

Renames "ubuntu-server" task -> "server" for Ubuntu 14.04

---

scripts/freebsd/vmtools.sh

For more info check: https://www.freebsd.org/cgi/man.cgi?loader(8)
autoboot_delay
Number of seconds autoboot will wait before booting.  Ifthis
variableis not defined,autoboot will default to 10 seconds.
If set to NO'', no autoboot will be automatically attempted
after processing/boot/loader.rc, thoughexplicit autoboot's
will be processed normally, defaulting to 10 seconds delay.
If set to 0'',no delay will be inserted, but user still will
be able to interrupt autoboot process and escapeinto the
interactive modeby pressing some key onthe console while ker-
nel and modules are being loaded.
If set to -1'', no delay will be inserted and loader will
engage interactive mode only if autoboothas failed for some
reason.

Speed up booting process for FreeBSD saving 10 seconds in boot time

---

centos-7.2-x86_64.json

As per #667, HGFS isn't shipped with open-vm-tools so we need to use
the propietary tools if we want shared folders and I believe most
bento users would agree they want those.

Partially revert #638. Fix #667

---

bin/bento

Discovering the plugins via a shellout is brittle and regardless of
plugin what we really care about is whether it's linux or osx. 
File under: Don't be clever

Autodetection is for the birds

---

scripts/sles/remove-dvd-source.sh
sles-12-sp1-x86_64.json
sles-12-x86_64.json

1) Suse is Oracle style now and requires a token to download the image
2) Fix the vm tools installs

Fix SLES builds

---

macos-10.12.json
scripts/macosx/update.sh

Added Sierra packer template (macos-10.12.json) and updated scripts/macosx/updates.sh to support Sierra.
I've tested this on Virtualbox but don't have access to Parallels or VMware.

macOS Sierra support

---

scripts/common/minimize.sh
scripts/ubuntu/cleanup.sh

In response to issue #717 
The kernel I noticed myself. The others are care of boxcutter. Thanks folks:
- On Ubuntu make sure we cleanup kernels version 4.X instead of just 3.X. This frees up 200+ megs on disk and 50 megs on the image
- Cleanup /var/log files. < 100k on disk
- Purge additional packages. 4.5 megs on disk
- Purge docs packages. 3 megs on disk
- Purge docs
- Purge caches
- Whiteout not only /, but /boot
With these changes my original Ubuntu 16.04 image was 682.7MB and the final file is 481.9MB.

Reduce size of Linux images

---

fedora-23-i386.json
fedora-23-x86_64.json
fedora-24-i386.json
fedora-24-x86_64.json
scripts/fedora/yum.sh

If you use chef with test-kitchen on bento fedora boxes and invoke the resource `package`, it will fail because of missing `yum` (there is no `dnf` provider yet, https://github.com/chef/chef/issues/3201).
This PR is a workaround for the time till chef gets the `dnf` provider.
See https://github.com/chef/chef/issues/5492 for details and logs

Avoid breaking of chef package resource on fedora

---

http/opensuse-leap-42.2/autoinst.xml
opensuse-leap-42.2-x86_64.json
scripts/opensuse/cleanup.sh

- Had to reduce the number of packages that is cleaned up for OpenSUSE 42.2.

Updated to OpenSUSE Leap 42.2

---

fedora-25-i386.json
fedora-25-x86_64.json
scripts/fedora/cleanup.sh
scripts/fedora/fix-slow-dns.sh

Tested x86_64 and i386 builds on:
- Parallels Desktop for Mac Pro 12.1.1
- VMware Fusion 7.1.3
- VirtualBox 5.1.6

Updated to Fedora 25

---

http/centos-6.8/ks.cfg
http/centos-7.3/ks.cfg

CentOS 7.3 includes `sudo-1.8.6p7-21` which disables requiretty by default.
CentOS 6 has not required this since at least 6.8.
See https://github.com/CentOS/sig-cloud-instance-build/pull/78 for more details.

Remove CentOS requiretty sudoers workaround, this is now the default

---

centos-7.3-x86_64.json
scripts/centos/vmware.sh

There isn't an easy way to grab the latest vmtools from the open web, in this case 10.1.0, so we're using Packer's File provisioner to sideload it just for 7.3 vmware-iso.
Fixes #742

Update VMware tools to fix CentOS 7.3 build

---

.travis.yml
scripts/freebsd/cleanup.sh
scripts/freebsd/minimize.sh

FreeBSD 10.3 image is too big (1.2Gb):
```
Andres-MacBook-Pro:bento andres$ ls -lah builds/
-rw-r--r--   1 andres  staff   1.2G Jan 31 11:26 freebsd-10.3.virtualbox.box
```
With this change the image is reduced by **670.8Mb**!
```
Andres-MacBook-Pro:bento andres$ ls -lah builds/
-rw-r--r--   1 andres  staff   558M Jan 31 10:58 freebsd-10.3.virtualbox.box
```
The causes are the following:
```
root@freebsd-10:/boot/kernel # du -sh
509M    .
root@freebsd-10:/boot/kernel # rm *.symbols
root@freebsd-10:/boot/kernel # du -sh
97M    .
```
According to FreeBSD docs this can be safely removed as shown [here]
Also `/var/cache/pkg` can be deleted as it's only used for storing cache of installed packages:
```
root@freebsd-10:/var/cache # du -d 1 -h
72M    ./pkg
72M    .
```
Then the …

Reduce FreeBSD 10.3 image size

---

fedora-24-i386.json
fedora-24-x86_64.json
fedora-25-i386.json
fedora-25-x86_64.json
scripts/fedora/cleanup.sh
scripts/fedora/yum.sh

Remove more packages and leftover files, but build the package cache. End result is the image is slightly smaller, but the first install on the image should be faster

Better cleanup for the Fedora boxes

---

oracle-6.8-x86_64.json

json is for 6.8 oracle, but box_basename was 6.7
Signed-off-by: JiSoo Kim <jskim910118@gmail.com>

Fixing typo on box_basename for oracle linux 6.8 x86_64

---

macos-10.12.json

I'm not 100% sure if this is an issue--it might need to be confirmed but I could not finish building this box without this fix…
---
For some reason with Pack 0.12.3, the current `"memory"` user variable
is not being picked up and a default value of `1024` is always being
used, leading to macOS 10.12 not being able to finish its installation.
For some reason, changing the user variable from `"memory"` to almost
anything else (in this case, `"memsize"`) allows the user variable to be
picked up.
Note that this was observed with the `vmware-iso` builder and may be the
only affected one. I verified this behavior by running:
```
env PACKER_LOG=1 bundle exec bento build --only=vmware-iso --debug macos-10.12
```

[macos-10.12] Allow Packer to pick up memory user var.

---

centos-6.9-i386.json
centos-6.9-x86_64.json

Checksums didn't match. Now they do.

Fixing checksums for CentOS 6.9

---

debian-9.0-amd64.json

There's going to be 10 more releases of debian 9 before they're done.

Rename debian-9 to debian-9.0

---

scripts/ubuntu/cleanup.sh

linux-firmware is the killer fix here, but we get maybe another meg from the others

Drop 100 megs from the Ubuntu images

---

scripts/ubuntu/sudoers.sh

This pull request addresses issue #711.
It moves the settings for the `vagrant` user out of `/etc/sudoers` and into a file under `/etc/sudoers.d`.
Incidentally, this is the practice currently followed by the Debian bento boxes, so this change brings Ubuntu into line.
Thanks for your consideration.
Signed-off-by: Brian Knight <brianknight10@gmail.com>

Move Ubuntu user settings into sudoers.d

---

README.md
centos-7.3-x86_64.json
http/centos-7.3/ks.cfg

Due to the way Hyper-V handles virtual switches the name of the virtual switch must be passed as an environment variable. 
Can be obtained via: ```Get-VMSwitch``` in PowerShell. 
Example packer build command
```
packer build --only=hyperv-iso -var 'hyperv_switch="Your vSwitch Name"' .\centos-7.3-x86_
64.json
```
Several changes were required for the ks.cfg
* ```network --bootproto=dhcp --onboot=on --device=eth0``` forces the network to be available for %post
* ```reboot --eject``` forces ejection of the install media after first reboot, otherwise you end up in the installer again

Hyper-V Support for CentOS 7.3

---

http/ubuntu/preseed.cfg

By default the Ubuntu installer sets the repository hostnames in `/etc/apt/sources.list` to the country-specific mirrors based on the locale chosen, which for this image is `us.archive.ubuntu.com`.
The US mirror is slow for users outside the US, so a better option is to use `archive.ubuntu.com`, which automatically resolves to the closest official country mirror to them. This is also the hostname used in the official Ubuntu Docker images.
Fixes #810.

Make Ubuntu APT use archive.ubuntu.com rather than the US domain

---

index.md

http://chef.github.io/bento/ is out of date.
Bento organization's pre-built boxes url points to https://app.vagrantup.com/bento instead of 
https://atlas.hashicorp.com/bento/.
Bento organization pre-built boxes link points to atlas.
box images which are listed in pre built boxes are out of date.

Use app.vagrantapp.com instead of atlas in gh-pages

---

scripts/debian/networking.sh

Fixes https://github.com/chef/bento/issues/851 (I think).
This disables a [hack](http://6.ptmc.org/164/) that prevents automatic udev rule creation by placing a folder where there should be a file with udev rules in it. The existence of that folder prevents `libudev-dev` from being installed properly in debian stretch.
I *think* it's no longer necessary to apply this hack to prevent rules from being automatically created, according to comments in #851, but someone should corroborate that claim.

Disable udev hack on Debain Stretch+

---

http/ubuntu/preseed-hyperv.cfg
ubuntu-16.04-amd64.json

**1) Don't use Hyper-V preseed on virtualbox/vmware Ubuntu 16.04 boxes.**
This reverts the change inadvertently made in #844.
**2) Make Hyper-V Ubuntu boxes use archive.ubuntu.com too**
Applies the fix from #838 to the Hyper-V preseed config added in #844.
Fixes #864.

Use correct preseed config with virtualbox/vmware Ubuntu 16.04 boxes 

---

centos-7.3-x86_64.json
http/centos-6.9/ks.cfg
http/centos-7.3/ks.cfg

Avoid disk checks on installation and remove more firmware files to slim the disk sizes down.

Speed up and slim CentOS builds

---

builds.yml
http/opensuse-leap/autoinst.xml
opensuse-leap-42.3-x86_64.json

Update for opensuse 42.3 and use a generic autoinst dir

---

sles-12-sp2-x86_64.json

Replaced "en_US-8" to "en_US" to avoid manual intervention during unattended builds.

Fix wrong en_US-8 boot parameter

---

opensuse-leap-42.3-x86_64.json

Standardizing on 1024MB as default memory

---

freebsd/http/freebsd-11/installerconfig

There is a dedicated ZFS filesystem in zroot/usr/home and mounted under ``/usr/home``, but the ``vagrant`` user uses ``/home``.
On FreeBSD, both variants are valid, but since a dedicated dataset exists, it is less bewildering for FreeBSD users to use that as the home directory location.
For compatibility and convenience, there is also a symlink from ``/home`` to ``/usr/home``.

Use the zroot/usr/home file system as location for the vagrant home directory

---

sles/sles-12-sp2-x86_64.json
sles/sles-12-sp3-x86_64.json

Fixes incorrect XML path caused by cffc78107e71efe747a76ee5911bd9331cea458d.

Fix SLES autoinst.xml path.

---

_common/virtualbox.sh

This is consistent with the other builder scripts. Also, removing the
hardcoded /home/vagrant string allows non-vagrant user images to be
created.

Set default HOME_DIR in virtualbox.sh

---

ubuntu/ubuntu-14.04-amd64.json
ubuntu/ubuntu-16.04-amd64.json
ubuntu/ubuntu-17.04-amd64.json

Noticed when trying to build a hyper-v version of the ubuntu 16.04 AMD64 box that the path was wrong for the preseed file. This PR updates the path to where you should no longer get the `Failed to retrieve the preconfigureation file` error during the build process.

🚑 Update path to preseed-hyperv.cfg to remove ubuntu/ folder path

---

sles/sles-12-sp3-x86_64.json

fixing bad language-setting in vmware-iso builder of sles/sles12-sp3-x86_64
* this fixes issue #932

fixing bad language-setting in sles/sles12-sp3-x86_64

---

sles/sles-12-sp2-x86_64.json
sles/sles-12-sp3-x86_64.json

* fixing issue #936
* tested on VMware Workstation 12 Pro (for sles-12-sp3-x86_64)

fixing guest_os_type for sles-12-sp(2|3)-x86_64 setting it to sles12-64

---

opensuse/scripts/cleanup.sh

The cleanup scripts for openSUSE were not disabling udev rules similar to how CentOS is set up.  This creates a problem when mutating the box (using `vagrant-mutate`) for use with libvirt.  The box will hang because the network can't initialize properly.
This is my first PR to bento, so if there is a specific format or anything I should tweak just let me know.

Fix network persistence on openSUSE

---

freebsd/http/freebsd-11/installerconfig
freebsd/scripts/cleanup.sh

This speeds up box creation a lot.  The box creation is using pkg(1)
to install software so doesn't need source files.  It doesn't make much
sense installing all the source files and then deleting them during
cleanup stage.

Don't install src while creating box

---

freebsd/freebsd-10.3-amd64.json
freebsd/freebsd-10.3-i386.json
freebsd/freebsd-10.4-amd64.json
freebsd/freebsd-10.4-i386.json
freebsd/freebsd-11.1-amd64.json
freebsd/freebsd-11.1-i386.json

The value for `output_directory` in the VMware section of the FreeBSD templates (freebsd/*.json) is spelled incorrectly as `-vmare` which just results in an inconsistent default name when building everything. This PR simply updates it to the correct spelling of `-vmware`.

Fixed a mis-spelling of `output_directory` inside the FreeBSD templates.

---

macos/macos-10.12.json
macos/macosx-10.10.json
macos/macosx-10.11.json
macos/macosx-10.9.json
macos/scripts/autologin.sh
macos/scripts/support/set_kcpassword.py

Scripts are taken from the project https://github.com/boxcutter/macos
Having "autologin" set to "true" (the default behavior), we will get the "vagrant" user's GUI session started automatically on the VM boot.
It might be required for different provisioning purposes. 
For example, if we use such VM as an [Omnibus](https://github.com/chef/omnibus) builder, then `dmg` packager will fail if there is no GUI session running on the machine:
```
[Compressor::DMG] I | 2018-01-17T09:37:00+01:00 | Rendering `/Users/vagrant/.bundle/ruby/2.4.0/omnibus-fff89b2e4b0c/resources/dmg/create_dmg.osascript.erb' to `/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/myproj20180117-464-rvez6y/create_dmg.osascript'
[Compressor::DMG] I | 2018-01-17T09:37:01+01:00 | Packaging time: 15.551s
The following shell …
```

Enable autologin for vagrant user on macOS

---

freebsd/freebsd-10.3-amd64.json
freebsd/freebsd-10.3-i386.json
freebsd/freebsd-10.4-amd64.json
freebsd/freebsd-10.4-i386.json
freebsd/freebsd-11.1-amd64.json
freebsd/freebsd-11.1-i386.json

Disable uploading vbox guest additions ISO, which is installed via pkg

---

builds.yml
hardenedbsd/hardenedbsd-11-amd64.json
hardenedbsd/http/hardenedbsd-11/installerconfig
hardenedbsd/scripts/cleanup.sh
hardenedbsd/scripts/minimize.sh
hardenedbsd/scripts/postinstall.sh
hardenedbsd/scripts/sudoers.sh
hardenedbsd/scripts/update.sh
hardenedbsd/vagrantfile_templates/hardenedbsd.rb

These new files are based on the files in the freebsd folder.
I added the new platform also to builds.yml.
Tested with:
```packer build -only=virtualbox-iso hardenedbsd-11-amd64.json```

add new platform: HardenedBSD 11

---

hardenedbsd/hardenedbsd-11-amd64.json

Previously we fetched the ISO from the LAST folder,
which will not contain the current ISO file after the next release.

HardenedBSD: fetch from a mirror directory that works in the future

---

macos/macosx-10.10.json
macos/macosx-10.9.json

Starting since VMware Tools 10.0.12, there is a dedicated image for
guest OS X 10.10 and older: `"darwinPre15.iso"`
https://docs.vmware.com/en/VMware-Tools/10.0/rn/vmware-tools-10012-release-notes.html
Otherwise, the installation fails, because `darwin.iso` supports only macOS 10.11 and higher.
I've verified that on VMware Fusion 10.1.1. There is a chance that this PR will break the compatibility of Packer templates with VMware Fusion 8.* and older (and an appropriate versions of VMware Workstation missing `"darwinPre15.iso"`)

Install VMware Tools on OS X 10.10 and earlier from a specific ISO

---

freebsd/freebsd-10.3-amd64.json
freebsd/freebsd-10.3-i386.json
freebsd/freebsd-10.4-amd64.json
freebsd/freebsd-10.4-i386.json
freebsd/freebsd-11.1-amd64.json
freebsd/freebsd-11.1-i386.json
freebsd/scripts/cleanup.sh

Fixes #1009 
- the default for `tools_upload_flavor` is an empty string, we can remove this line as it's uploading a useless ISO
- remove any ISOs from the vagrant user's home dir just in case

Don't upload ISO for VMware and cleanup any ISOs

---

debian/scripts/networking.sh
ubuntu/scripts/networking.sh

- Fix #1003 
- Fix #1004 
For Debian family operating systems that ship with SystemD we create `/etc/network/interfaces.d/eth0.cfg` but don't clean up any prior `en*` entries in `/etc/network/interfaces`. Instead, we have gotten rid of the `eth0.cfg` and opted to rely on `/etc/network/interfaces`. As an improvement, the code has also been re-organized to only run the necessary steps on platforms that require them and we're now aligning Debian with Ubuntu so it's `eth0` across the board.

Simplify and cleanup issues with disabling Predicatable Interface Naming

---

opensuse/http/autoinst.xml
opensuse/opensuse-leap-42.3-x86_64.json

Fix #985 which was due to snapper (via btrfs) creating snapshots on a small (20GB) drive. Automatic snapshots really aren't sensible for our goals of sane base box defaults and thankfully AutoYast has a [toggle](https://www.suse.com/documentation/sles-12/singlehtml/book_autoyast/book_autoyast.html#CreateProfile.Partitioning.config). Also bumping the disk size to be in line with other platforms.

Fix #985 - Disable snapshots

---

opensuse/opensuse-leap-42.3-x86_64.json
opensuse/scripts/vagrant_group.sh

openSUSE does not create a group with the same name as the user and this
breaks some assumptions that user files are owned by 'vagrant:vagrant'.
As such, lets create such a group and put the vagrant user in it.

opensuse: Create a new 'vagrant' group for vagrant user

---

fedora/scripts/cleanup.sh

When using a box generated from the fedora-27.json, the network.service fails to restart cleanly because there are leftover network configuration files for non-existent devices.  This update removes anything that is non-loopback related.

Clean up network configs

---

centos/http/7/ks.cfg
fedora/http/ks.cfg

I think this one additional package do not hurt and can be save download size during update

fedora, centos, rhel: added deltarpm to kickstart files

---

fedora/fedora-28-x86_64.json
fedora/http/ks-fedora28.cfg
fedora/scripts/build-tools.sh
fedora/scripts/cleanup.sh

Fixes #1034.
I only tested with Virtualbox, but I didn't change anything particular in the builder config so I hope the other providers keep working. Also, this needs to be built with Virtualbox 5.2.10 because older versions of the guest additions don't support Linux 4.16 and fail to compile.

Add Fedora 28

---

fedora/scripts/cleanup.sh

We install additional software during the build process, such as Perl modules. Removing Perl at cleanup causes an unintended removal of those packages, therefore I changed cleanup.sh to not remove "make" and "perl". This is in line with other cleanup scripts like that from centos.

Fix Fedora cleanup script not to cause unintended software removal.

---

centos/scripts/cleanup.sh

`yum update` keeps several kernel versions installed at the same time by default (installonly_limit). 
So, `bento/centos-6.9` image v201803.24.0 has two installed kernels: `kernel-2.6.32-696.el6.x86_64` and `kernel-2.6.32-696.23.1.el6.x86_64` . 
Removal of the unused one would reduce the image size by about 50 megs.
1. The proposal is to delete via `package-cleanup` from `yum-utils`, which probably should take care for `kernel-uek`  in the Oracle Linux.
2. Alternative approach could be direct manipulation:
```bash
unused_kernels=("`rpm -q kernel kernel-uek | grep -v "\`uname -r\`"`")
if [ ${#unused_kernels[@]} -gt 0 ]; then yum remove -y ${unused_kernels[@]}; fi
```
```bash
[vagrant@localhost ~]$ rpm -qi kernel
Name        : kernel                       Relocations: (not relocatable) …
```

centos, rhel, oracle: remove previous kernels to minimize image size

---

windows/2008r2.json
windows/2012r2.json
windows/2016.json

Increase built time memory to 4GB on Windows boxes

---

centos/http/6/ks.cfg
centos/http/7/ks.cfg

'visudo -c' reports that /etc/sudoers.d/vagrant should have its mode set to 0440, but it is set to 0644.

Set correct permissions on /etc/sudoers.d/vagrant

---

opensuse/http/autoinst.xml
sles/scripts/cleanup.sh

* Addresses #1070 for openSUSE
* Implements the same fix in SLES as #943 did for openSUSE

openSUSE no space issue and SLES network persistence

---

ubuntu/scripts/cleanup.sh

This fixes the issue in:
https://github.com/chef/bento/issues/1062
I have not done backtesting on versions other than 18.04, but I can't see why it would cause any issues.

WIP: Blank netplan machine-id (DUID) so Ubuntu machines get unique ID generated on boot.

---

builds.yml
centos/centos-6.10-i386.json
centos/centos-6.10-x86_64.json

The last CentOS 6...can't come soon enough.

Update CentOS 6.9 -> 6.10

---

sles/http/sles-11-sp4-x86_64-autoinst.xml
sles/http/sles-12-sp2-x86_64-autoinst.xml
sles/http/sles-12-sp3-x86_64-autoinst.xml
sles/sles-11-sp4-x86_64.json
sles/sles-12-sp2-x86_64.json
sles/sles-12-sp3-x86_64.json

* Implements the same disk space fixes that opensuse has
* Bring back SLES 11 SP4 because it is not EOL. General support ends in 2019, long term in 2022 (see [here](https://www.suse.com/lifecycle/))

Fix disk space on SLES 12 and bring back SLES 11

---

windows/2016.json

This fixes an issue where an unattended install was failing.
Signed-off-by: John Jelinek <jjelinek@containerstore.com>

Windows 2016: Point to the correct Autounattend.xml

---

centos/http/7/ks.cfg

Disable consistent naming in RHEL/CentOS 7 so we always have an eth0 interface.

Disable consistent naming in RHEL/CentOS 7

---

centos/centos-5.11-i386.json
centos/centos-5.11-x86_64.json
centos/http/5/ks.cfg
centos/scripts/enable_vault.sh

Adds CentOS 5 once again, since some still must test on it
Excludes SELinux
Configures yum to use the Vault repos to install packages
Lack of CentOS 5
Inability of CentOS five image to install packages
Note for @cheeseplus I'm 99% sure I removed all hard-coded values and replaced them with variables, but you might want to check just to make sure. :)

Add CentOS 5 to the repo again

---

freebsd/freebsd-11.2-amd64.json

We weren't setting `name` and so boxes were using the `template_name` instead which broke the build/test/upload pipeline.

Add the name key for FreeBSD 11.2, fix build/upload

---

ubuntu/ubuntu-18.04-amd64.json

Name shouldn't change for patch releases, s/18.0.41/18.04/

Don't include the patch release in name

---

centos/http/5/ks.cfg

It is already installed in 6 and 7 by default. Adding it to the
CentOS 5 kickstart so it will be installed there too.
Adds curl to the default package list in the CentOS 5 kickstart
Lack of curl

Add curl to CentOS 5 install

---

hardenedbsd/hardenedbsd-11-amd64.json

Adds `name` key which was missing and causing uploads to be incorrectly using `template` value.

Adding name field to fix build/upload

---

debian/scripts/cleanup.sh

The `installation-report` package generates installation report, installer related choices and debug infos into `/var/log/installer/`.
It takes about 15M disk space for debian 9.5 builds.
Fixes #1129

update debian provision: purge installation-report in cleanup.sh

---

builds.yml
fedora/fedora-29-x86_64.json
fedora/http/ks-fedora29.cfg

This changes include support for creating fedora-29 boxes with libvirt. It also includes fedora-29 in builds.yml so the fedora-29 boxes are publicly available in vagrant cloud.

Support for fedora29 in libvirt and public release

---

windows/2016.json

Adds the ability to build using vmware-iso (aka vmware desktop/fusion)
windows 2016 only has virtualbox-iso builder

add vmware-iso to windows 2016

---

.gitignore

I'm the maintainer of https://github.com/laravel/homestead and https://github.com/laravel/settler projects and would like to hard link my provisioning scripts without interfering with this repository.
Currently we just copy and delete our script as needed. This pull request would allow us to accept https://github.com/laravel/settler/pull/192 which creates a hard link. Both pull requests would allow us to continue our respective workflows with a lesser chance of me doing something goofy on my end. :D
Thanks for all the work that goes into this project. <3

Add homestead script to git ignore

---

debian/scripts/networking.sh
ubuntu/scripts/networking.sh

For justification, see
https://github.com/sipwise/netscript/commit/4844134152e5195e3162c4df28d6fc3175866787
This change removes an option that leaves behind a file called /etc/default/grube
It was probably intended to be `sed -i -e` but only `sed -i` is required
As above

remove sed -ie option command that leaves /etc/default/grube

---

debian/scripts/update.sh
ubuntu/scripts/update.sh

There is a race to disable apt-daily before it can trigger its own apt
process that grabs the apt lock.
Running apt-get update first adds more time for apt-daily to trigger
before it gets disabled. Then a subsequent apt command after the
disablement of apt-daily can fail grabbing the apt lock.
Move the apt-get update later and disable apt-daily earlier to give us a
better chance of winning the race.
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
[Please describe what this change achieves]
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

Disable apt-daily earlier.

---

debian/debian-9.8-amd64.json
debian/debian-9.8-i386.json
debian/debian-9.8-ppc64el.json
debian/http/debian-9/preseed.cfg

Fix Debian 8 build that is currently asking for user input, and have a separate preseed file for Debian 9 that does not have this workaround.
https://github.com/chef/bento/issues/1190

Fix Debian 8 builds to not ask for confirmation, and use a separate preseed file for Debian 9.

---

packer_templates/centos/http/6/ks.cfg
packer_templates/centos/http/7/ks.cfg
packer_templates/debian/http/debian-8/preseed.cfg
packer_templates/debian/http/debian-9/preseed.cfg
packer_templates/fedora/http/ks-fedora29.cfg
packer_templates/ubuntu/http/preseed.cfg

Installing rsync allows users to utilize kitchen-sync [1] to speed up
test-kitchen sync tasks. Unfortunately, none of the bento boxes include rsync so
this adds it. It should had a minimal amount of disk space (less than a few MBs)
[1] https://github.com/coderanger/kitchen-sync
Signed-off-by: Lance Albertson <lance@osuosl.org>
Install rsync package on most bento boxes.
n/a

Install rsync on popular boxes

---

builds.yml
packer_templates/freebsd/freebsd-11.3-amd64.json
packer_templates/freebsd/freebsd-11.3-i386.json

Add recently released FreeBSD 11.3 and mask `freebsd-11` to use 11.3.
I was only able to test it with Virtualbox.
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

Add FreeBSD 11.3

---

packer_templates/debian/debian-9.9-amd64.json
packer_templates/debian/debian-9.9-i386.json
packer_templates/debian/debian-9.9-ppc64el.json

Signed-off-by: Christopher A. Snapp <csnapp@chef.io>
Debian 9 is no longer available via the release tree and needs to be pulled from archive.
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

Modify Debian 9 URL to point to archive

---

packer_templates/centos/centos-5.11-i386.json
packer_templates/centos/centos-5.11-x86_64.json
packer_templates/centos/centos-6.10-i386.json
packer_templates/centos/centos-6.10-x86_64.json
packer_templates/centos/centos-7.6-x86_64.json
packer_templates/ubuntu/ubuntu-16.04-amd64.json
packer_templates/ubuntu/ubuntu-18.04-amd64.json
packer_templates/ubuntu/ubuntu-18.10-amd64.json
packer_templates/ubuntu/ubuntu-19.04-amd64.json

Signed-off-by: Joe Ferguson <joe@joeferguson.me>
Resolves the Hyper-V issues brought up in #1194 with wrong params/variable names
Resolves #1194
Here's a Gist of running `packer validate ...` against each of the changed files. Looks like there are some VMware issues to be addressed, no errors or warnings for Hyper-V.
* Centos: https://gist.github.com/svpernova09/c57c1bc708057c4322e47e8bd670b8b3#file-centos-txt
* Ubuntu: https://gist.github.com/svpernova09/c57c1bc708057c4322e47e8bd670b8b3#file-ubuntu-txt

Update Hyper-V Parameters to new conventions

---

packer_templates/ubuntu/http/preseed-hyperv.cfg
packer_templates/ubuntu/http/preseed.cfg

Same change as #1125 but moved the `ifupdown` package to `packer_templates/ubuntu/http/preseed.cfg` and `packer_templates/ubuntu/http/preseed-hyperv.cfg`
As requested in #1125 to move this package addition to preseed

Ubuntu - Install ifup/ifdown utilities for private networks

---

packer_templates/fedora/fedora-30-x86_64.json
packer_templates/fedora/scripts/install-supporting-packages.sh

Fedora >= 30 requires libxcrypt-compat to be installed to provide libcrypt.so.1 for Chef.
The the libxcrypt-compat package needs to be installed for Chef to work with Fedora 30 so add a script to do it and add it to the packer build.
n/a

Fix the Fedora 30 box for Chef

---

packer_templates/centos/http/8/ks.cfg

This installs the legacy network scripts which [Vagrant still requires it](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/pld/cap/change_host_name.rb#L22) seems for the ``network`` systemd service. The ``network-scripts`` package provides the ``network.service`` systemd unit which resolve the issue. That probably should be fixed upstream at some point to use ``nmcli`` or something else.
Signed-off-by: Lance Albertson <lance@osuosl.org>
When starting a new VM with the latest CentOS 8 image I have the following issue:
``` console
-----> Starting Kitchen (v2.3.3)
-----> Creating <all-centos-8>...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-8'...
==> default: Matching MAC address for NAT networking...
==> default: …
```

Add network-scripts package for CentOS 8

---

packer_templates/centos/scripts/cleanup.sh

This PR fixes the problem as described in issue #1230 (and using the same solution), whereas `vagrant up` hangs forever for CentOS 7.7 boxes due to the `cleanup.sh` script on build specifying an ambiguous `eth` parameter as network type for `nmcli`.

Fix CentOS 7.7 hang on start due to ambiguous "eth" network type

---

packer_templates/macos/macos-10.12.json
packer_templates/macos/macosx-10.11.json

Sorry. I should've included this in my other PR, but didn't think of it until you mentioned "cleaning up the warnings". This replaces the "usb.present" option that's explicitly specified in the "vmx_data" for the macos templates with the "usb" option. I'm familiar with these options because I'm the author of their related PRs in packer, so...might as well spread the syntax everywhere.

Updated the macos templates to use the "usb" option to enable usb instead of "vmx_data" for the vmware-iso builders.

---

packer_templates/windows/windows-10.json
packer_templates/windows/windows-2008r2.json
packer_templates/windows/windows-2012r2.json
packer_templates/windows/windows-2016.json
packer_templates/windows/windows-2019.json
packer_templates/windows/windows-7.json

This updates the windows templates to change the setting of scsi options using "vmx_data" with the "disk_adapter_type" option in order to clean up warnings during template validation. The default setting of "lsisas1068" was retained in order to not actually change the semantics of anything. This commit is 1eb7739ebffa61f9dde2050f07b7f0e1a676d663 in case that's easier to see the specific changes.
The second commit changes the tabs in the windows templates to 2-space indents so that it follows the same style of the linux templates and is consistent. I made it a second commit in case you guys don't care for this type of change to these window templates. Let me know if you want me to restore the tabs or split it into a different PR if that's the case. This commit is …

Updated windows templates to replace scsi settings applied by "vmx_data" with the "disk_adapter_type" option in order to clean up validation warnings

---

packer_templates/windows/scripts/base_setup.ps1

I've run into an infinite wait scenario when trying to build without the additional line added. While debugging I ran this script from an Administrator Powershell window and the error was always the same, the WinRM -quickconfig command doesn't seem to be getting the profile override so isn't allowing WinRM to be enabled preventing the initial Packer wait for WinRM to succeed.

Change profile to Private to avoid infinite wait

---

packer_templates/debian/debian-10.2-amd64.json
packer_templates/debian/debian-10.2-i386.json

A quick update to the Debian 10.2 release. Additionally split the preseed configuration to have one configuration per major-release (currently 8, 9, 10).
-

upgrading debian 10.1 -> 10.2 and use a separate preseed cfg

---

packer_templates/freebsd/scripts/postinstall.sh

Remove customized kern.hz as it will be automatically adjusted
Remove customized kern.hz as it will be automatically adjusted. It will be automatically set to 100 in a VM environment.

Remove customized kern.hz as it will be automatically adjusted

---

packer_templates/_common/motd.sh

The message when login is a 404 url.
I updated the url.

bugfix: fix welcome message 404

---

packer_templates/freebsd/freebsd-11.3-amd64.json
packer_templates/freebsd/freebsd-11.3-i386.json
packer_templates/freebsd/freebsd-12.0-amd64.json
packer_templates/freebsd/freebsd-12.0-i386.json
packer_templates/freebsd/freebsd-12.1-amd64.json
packer_templates/freebsd/freebsd-12.1-i386.json

When booting up a FreeBSD template, the default "boot_command" creates two memory disks and then executes `dhclient` to setup a network interface. When setting up the interface, `dhclient` needs to write some files. One of these files is the lease file which caches the requested dhcp lease and is handled by the `-l` parameter. Another one of these files is the pidfile which stores the current pid so that it can interact with an already existing instance if necessary. Since this isn't explicitly specified, `dhclient` will use `/var/run/dhclient.$interface.pid` by default which is read-only. This seems to result in some builds blocking indefinitely while waiting for a lease.
This PR simply adds the `-p` parameter to tell `dhclient` to write its pidfile into the writable `/tmp` directory …

Modified the boot_command for all of the FreeBSD templates to include the pidfile path when executing dhclient.

---

packer_templates/ubuntu/scripts/vmware.sh

The script was partially modified to use open-vm-tools instead of the legacy "official" vmware tools, but missed changing to the different service name that open-vm-tools uses.

Replace legacy service name with open-vm-tools

---

README.md
packer_templates/windows/answer_files/10/Autounattend.xml
packer_templates/windows/answer_files/2012_r2/Autounattend.xml
packer_templates/windows/answer_files/2016/Autounattend.xml
packer_templates/windows/answer_files/2019/Autounattend.xml
packer_templates/windows/windows-10.json
packer_templates/windows/windows-2012r2.json
packer_templates/windows/windows-2016.json
packer_templates/windows/windows-2019.json

This modifies some Windows templates (10, 2012_r2, 2016 and 2019) to add "qemu" builder. This is based on the work of [Bob Tanner](https://grot.geeks.org/tanner/packer-windows)
For example, with this PR you can use :
```
packer build --only=qemu windows-2019.json
```
**IMPORTANT** : You must download [the iso image with the Windows drivers for paravirtualized KVM/qemu hardware](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso) before starting this builder.

Add "qemu" builder for Windows 10, 2012R2, 2016 and 2019

---

packer_templates/sles/sles-15-sp1.json
packer_templates/sles/sles-15.json

Adding necessary qemu-args in order to mount additional iso used within autoyast 
#1252

fix: adding qemuargs to mount secondary drive

---

packer_templates/_common/minimize.sh

Block count were returned assuming 1 bloc = 1 KB, but in the `dd` command, blocks of 1MB were written. This results in 1000x write operation.
Block count should be returned in MB.
https://github.com/chef/bento/issues/1175
- [x ] Bug fix (non-breaking change which fixes an issue)

Incorrect calculation of block count

---

packer_templates/oraclelinux/oracle-7.7-x86_64.json

Oracle changed the behavior for the NAT network device
after rebooting the 1st time. enp3 is used during the kickstart
and eth0 after the reboot. Packer cannot connect via SSH, due
to missing network configuration for eth0.

oraclelinux-7: added kernelparameter for kickstart

---

packer_templates/freebsd/scripts/minimize.sh

Don't need to periodically check the space left, dd(1) will
automatically exit after it cannot write to the disk anymore.
This mitigate the issue that fs may reserve some space so the
available space size will never get to 0.

FreeBSD minimize: let dd(1) automatically exit on disk full

---

packer_templates/windows/windows-10.json
packer_templates/windows/windows-2012.json
packer_templates/windows/windows-2012r2.json
packer_templates/windows/windows-2016.json
packer_templates/windows/windows-2019.json

Explicitly sets value matching Packer default of approximately 40GB (40000 megabytes)
Removes deprecated iso_checksum_type
Removes hardcoded `sha1:` prefixed to iso_checksum as Packer can infer the type and supports getting checksums from a file: URI which this would have broken.
https://www.packer.io/docs/builders/virtualbox/iso#iso_checksum
The "public" boxes all supported disk_size but the Windows ones for some reason did not. Added in appropriate block to all providers and variables blocks.
Fixes #1294

Enabling disk size overrides for Windows

---

packer_templates/windows/cookbooks/packer/recipes/vm_tools.rb

vm_tools.rb was incomplete for the vmware section -- the powershell didn't execute anything after unpacking the iso file.  There were some other slight problems with escaping in the ruby here-document block, and the vmware section was incorrectly reporting that it was installing vbox addons.
I don't know if there are existing issues this addresses

Fix vm_tools recipe

---

README.md

The examples in the README indicate the OS directories but it isn't (wasn't) specifically clear where these directories were.  They could be easily found by looking around in the repository - `packer_templates/` is fairly logical but it's easiest if it's documented.

Add packer_templates/ directory to README examples

---

packer_templates/_common/virtualbox.sh

The build was failing for CentOS 8.2 because the necessary dependencies for virtualbox guest additions weren't being installed. It seems that a `dnf` default has changed and it now requires an explicit `--skip-broken` to ignore missing packages.

Fix virtualbox additions build failure on CentOS 8.2

---

packer_templates/fedora/fedora-31-x86_64.json
packer_templates/fedora/fedora-32-x86_64.json

Add qemuargs parameter for Fedora
Add qemuargs parameter for Fedora in order to use it during Fedora build (example : to load EFI firmware)
- [] Bug fix (non-breaking change which fixes an issue)

Add qemuargs parameter for Fedora

---

packer_templates/windows/windows-10gen2.json

Add qemu in Windows 10 Gen2 installation
With this PR you can create Windows 10 UEFI for qemu

Add qemu in Windows 10 Gen2 installation

---

packer_templates/fedora/fedora-33-x86_64.json
packer_templates/fedora/scripts/crypto-policy.sh

Fedora now [disables RSA](https://dev.to/bowmanjd/upgrade-ssh-client-keys-and-remote-servers-after-fedora-33-s-new-crypto-policy-47ag) cause it's considered as insecure
This PR sets the crypto mode as LEGACY
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] I have read the **CONTRIBUTING** document.
- [ X ] I have run the pre-merge tests locally and they pass.
- [ X ] I have updated the documentation accordingly.
- [ X ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.
- [] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

set fedora crypto policy to legacy

---

packer_templates/fedora/fedora-34-x86_64.json

Without this, vagrant cannot log into this boxes without some work as the default rsa key is rejected.
Signed-off-by: Lance Albertson <lance@osuosl.org>

Set crypto-policy to legacy on Fedora 34

---

packer_templates/debian/debian-10.11-arm64.json
packer_templates/debian/debian-11.1-arm64.json
packer_templates/debian/debian-9.13-arm64.json

Signed-off-by: Claude Becker <becker@phys.ethz.ch>
This PR adds support for Debian (11.1, 10.11, 9.13) on Apple M1 using Parallels.
Add Debian templates for arm64 architecture with Parallels to support Apple M1.
https://github.com/chef/bento/issues/1344

Add Debian arm64 templates for Parallels (Apple M1)

---

packer_templates/debian/debian-11.3-amd64.json

Add qemu_bios and boot_command variable for Debian 11.3 amd64
With this PR you can change BIOS and boot command for QEMU Debian 11.3 amd64 builds (example : for UEFI)
You can use these variables in order to boot in UEFI mode :
```
"qemu_bios": "/usr/share/ovmf/OVMF.fd",
"boot_command": "<wait><wait><wait>c<wait><wait><wait>linux /install.amd/vmlinuz auto=true url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/{{ user `preseed_path` }} hostname={{ .Name }} domain=vagrantup.com interface=auto vga=788 noprompt quiet --<enter>initrd /install.amd/initrd.gz<enter>boot<enter>"
```
Default qemu_bios value is "bios-256k.bin"
and in order to work on another builders, grub-installer/bootdev is set to "default" (because it is a different value on qemu).

feat(debian): add qemu_bios and boot_command variable for Debian 11.3

---

builds.yml
packer_templates/springdalelinux/http/8-netinst/ks.cfg
packer_templates/springdalelinux/springdalelinux-8.5-x86_64.json

Signed-off-by: Christopher Peterson <cspeterson@cspeterson.net>
Add Springdale Linux 8
Springdale 7 is already in the templates, but not 8. SDL8 is useful especially now that CentOS 8 is EOL.
I mostly just copied the Springdale 7 template to update to 8
Springdale does not publish a full ISO for 8.x, only a netinstall, so I also had to use an alternate `ks.cfg` (modified from the included centos `ks.cfg`) which provides `url`.
To build this for VirtualBox requires providing the current testing version of VBox guest additions, as the current stable releases will fail to build with the current kernels (https://www.virtualbox.org/ticket/20488)
The situation is the same for building the current Rocky Linux box using these templates
I can verify that building this individually for VirtualBox …

Add Springdale 8

---

packer_templates/almalinux/almalinux-9.0-x86_64.json

Almalinux 9 builds were failing when running the network script to restart the network. The fix the network script implements isn't needed for version 9.

remove network script to fix errors - this script isn't needed.

---

packer_templates/_common/parallels.sh
packer_templates/almalinux/almalinux-9.0-aarch64.json

This pull request adds support for building AlmaLinux 9 aarch64 parallels vagrant boxes.
x86_64 images won't work on M1/M2 (arm) Macs, so this PR adds support for building an AlmaLinux 9 parallels box.  It mostly works, but the parallels tools do not currently support AlmaLinux 9. Once those are [updated](https://forum.parallels.com/threads/parallels-tools-do-not-install-on-rhel9.357546/page-2) the build should work properly. 
```
==> parallels-iso: Provisioning with shell script: ~/bento/packer_templates/almalinux/../_common/parallels.sh
==> parallels-iso: + HOME_DIR=/home/vagrant
==> parallels-iso: + case "$PACKER_BUILDER_TYPE" in
==> parallels-iso: ++ sed 's/^.\+ release \([.0-9]\+\).*/\1/' /etc/redhat-release
==> parallels-iso: ++ awk -F. '{print $1}'
parallels-iso: Parallels Tools …
```

Add support for AlmaLinux 9 aarch64 parallels box

---

builds.yml
packer_templates/ubuntu/ubuntu-22.10-amd64.json

Swap Ubuntu 21.10 for 22.10

---

packer_templates/rockylinux/rockylinux-9.1-x86_64.json

Update Rocky Linux from 9.0 to 9.1, as the former doesn't even build anymore due to the referenced ISO no longer being available.
This also includes a fix for VirtualBox 7, where access to the NAT local host from the VM must be enabled explicitly.

Update Rocky Linux from 9.0 to 9.1

---

packer_templates/amazonlinux/README_FIRST.md
packer_templates/amazonlinux/amazon-2-x86_64.json

The http variable without the dir causes failures and the instructions were a tiny bit wrong

Fix failing Amazon Linux builds

---

packer_templates/almalinux/scripts/cleanup.sh
packer_templates/almalinux/scripts/networking.sh
packer_templates/almalinux/scripts/update.sh
packer_templates/fedora/scripts/cleanup.sh
packer_templates/rockylinux/scripts/cleanup.sh
packer_templates/rockylinux/scripts/networking.sh
packer_templates/rockylinux/scripts/update.sh

Now that these are unique to Alma/Rocky remove all the junk for old centos, redhat, and oracle

Remove extra checks from alma/rocky scripts

---

packer_templates/freebsd/scripts/minimize.sh

We're always using lz4 so there's no need to shell out to find that out

Simplify the FreeBSD minimize script

---

packer_templates/centos/centos-stream-9-x86_64.json
packer_templates/centos/http/9-stream/ks.cfg

This PR adds a new template for CentOS Stream 9 (x86_64). I've tested building it locally with `packer 1.8.4` and `VirtualBox 7.0.4` (it requires the latter due to older guest addons not supporting the latest CentOS 9.x kernel).
https://github.com/chef/bento/issues/1391

Added CentOS Stream 9 (x86_64) template

---

packer_templates/scripts/debian/cleanup_debian.sh
packer_templates/scripts/fedora/cleanup_dnf.sh
packer_templates/scripts/rhel/cleanup_dnf.sh
packer_templates/scripts/rhel/cleanup_yum.sh
packer_templates/scripts/suse/cleanup_suse.sh
packer_templates/scripts/ubuntu/cleanup_ubuntu.sh

Signed-off-by: Cory Francis Myers <cory@freedom.press>
`/var/lib/dbus/machine-id` [MAY][1] be a symlink to `/etc/machine-id`.  If it isn't, however, we need to truncate it separately to avoid reuse.
[1]: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1818499.html
Fixes #1421.
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Chore (non-breaking change that does not add functionality or fix an issue)

fix: truncate `/var/lib/dbus/machine-id` in case it's separate from `/etc/machine-id`

---

packer_templates/pkr-builder.pkr.hcl

Signed-off-by: Michael Campfield <michael.campfield@mailbox.org>
In the locals data structure there is a string misspelling which is part of a value equality conditional test.
The lefthand of the comparison operation is an equality test against the string 'amazonlinux-2' .  However, the string amazonlinux-2 has a character addition typo with a 'u' added between the i and n of linux: amazonliunux-2.  
Rectifying this issue will cause the value test against amazonlinux-2 to evaluate correctly.  
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] I have read the **CONTRIBUTING** document.
- [X ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
Obvious fix.

rectify typo for amazonlinux in locals data structure comparison test

---

os_pkrvars/fedora/fedora-37-aarch64.pkrvars.hcl

Fixes an invalid boot command because of an excess `}`.

remove excess curly brace in fedora 37 aarch64

---

os_pkrvars/ubuntu/ubuntu-22.10-aarch64.pkrvars.hcl

Fixes the boot command to successfully boot ubuntu 22.10 on aarch64. Previously it would do nothing until the `c` in `nocloud` was typed, and then get a error because the command was invalid.

Fix boot command for ubuntu 22.10 aarch64

---

.github/CODEOWNERS
packer_templates/_common/vmware.sh
packer_templates/almalinux/scripts/cleanup.sh
packer_templates/amazonlinux/scripts/cleanup.sh
packer_templates/centos/scripts/cleanup.sh
packer_templates/debian/scripts/cleanup.sh
packer_templates/fedora/scripts/cleanup.sh
packer_templates/opensuse/scripts/cleanup.sh
packer_templates/oraclelinux/scripts/cleanup.sh
packer_templates/rockylinux/scripts/cleanup.sh
packer_templates/sles/scripts/cleanup.sh
packer_templates/ubuntu/scripts/cleanup.sh

backporting script fixes for machine-id in /var/lib/dbus

backport script updates

---

.github/workflows/pkr-bld-amazonlinux-x64.yml
.github/workflows/pkr-bld-hyperv-x64.yml
.github/workflows/pkr-bld-parallels-arm64.yml
.github/workflows/pkr-bld-parallels-x64.yml
.github/workflows/pkr-bld-virtualbox-arm64.yml
.github/workflows/pkr-bld-virtualbox-x64.yml
.github/workflows/pkr-bld-vmware-arm64.yml
.github/workflows/pkr-bld-vmware-x64.yml
AMZ_build_virtualbox-ovf.sh
CHANGELOG.md

Added a cleanup step in build pipelines for cancelled jobs that otherwise leave vm in place. This then causes errors on subsequent runs as the vm already exists by the same name.

Added a cleanup step in build pipelines

---

CHANGELOG.md
os_pkrvars/ubuntu/ubuntu-18.04-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-20.04-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-22.04-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-22.10-aarch64.pkrvars.hcl
packer_templates/pkr-sources.pkr.hcl
packer_templates/pkr-variables.pkr.hcl

Fails to load the VM due to processor type mismatch.  Resolves with tacking on -arm64 or whatever onto the OS type in the template.
This initially starts with boot failures due to the LSILogic disk type preventing the VMX from loading at the vmxrun stage.  Changing the disk to SATA (longer term solution), or the disk adapter to PVSCSI from LSILOGIC resolves this.  There's builtin support for SATA, so I go that direction.
Next, IDE support for CDROM's is removed in Fusion 13.  Not sure if this is an M1/M2 thing or VMWare Fusion 13 change, I've been out of things for a bit.  Regardless, changing to SATA resolves it.  Just copied the same coding pattern from logical drives.
At this point things seem to boot to the point where they get into the GRUB loader then divert into PXE - so it's …

Improve ARM64 Silicon OS X and Ubuntu ARM64 support for VMWare Fusion

---

packer_templates/scripts/debian/cleanup_debian.sh

The `cleanup_debian.sh` script was only removing kernel versions starting with `[234]` and thus not matching the current kernel versions 5 or 6. This PR suggests to match any version `[1-9]`.

Match any kernel version in debian purge command

---

os_pkrvars/opensuse/opensuse-leap-15-aarch64.pkrvars.hcl
packer_templates/http/opensuse/autoinst-uefi.xml

This adds a configuration for a build for openSUSE Leap 15.4 for aarch64 hosts. While this is likely to work with most of the providers that support aarch64 images, I have only tested this locally on VMWare Fusion on my M2 macbook. I don't currently have a parallels license to test with. If there are better ways to test this (maybe non-locally?), let me know.
No specific related issue at the moment but there are a few open about ARM support for various other distributions.
(I couldn't really find where/how to run local tests so please let me know if you want me to do some more testing)

Add build for opensuse aarch64

---

packer_templates/scripts/windows/provision.ps1

We need to execute \$guestToolsPath not \$guestTools. (\$guestTools is just an intermediate variable for setting \$guestToolsLog.)
Newer virtio-win.iso has E:\virtio-win-guest-tools.exe. From the code it seems like older virtio-win.iso has this file in  E:\driver. Made sure script works with both old and new virtio-win.iso.

provision.ps1: fixed virtio-win-guest-tools.exe installation

---

os_pkrvars/almalinux/almalinux-9-aarch64.pkrvars.hcl
os_pkrvars/rockylinux/rockylinux-9-aarch64.pkrvars.hcl

* updates `vmware_guest_os_type` for almalinux and rockylinux 9 aarch64 to match the vmware hardware profile which reliably results in a successful build
Neither rockylinux nor almalinux 9.x targets for aarch64 would build on vmware fusion 13.x with the current specified `vmware_guest_os_type` as centos is no longer an officially supported target os of VMWare it seems reasonable to adopt their RedHat targeted support when building EL derivative distros.
This change has been tested on Apple Arm64 hardware running VMWare fusion 13.0.2, similar changes might be desirable for the x86_64 targets as well, but I suspect that those guest hardware profiles are more generic and have fewer unanticipated compatibility issues.

Update vmware vars for el9 derivitives

---

os_pkrvars/ubuntu/ubuntu-22.04-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-22.04-x86_64.pkrvars.hcl

The https://releases.ubuntu.com/jammy/ubuntu-22.04.2-live-server-amd64.iso address is no longer available (404). Since August 2023, there is a .3 release.

Update Ubuntu 22.04 `iso_url`

---

packer_templates/pkr-builder.pkr.hcl
packer_templates/scripts/_common/parallels_post_cleanup_debian_ubuntu.sh

When using [this Ubuntu Vagrant box](https://app.vagrantup.com/bento/boxes/ubuntu-22.04/versions/202303.13.0) with Parallels Desktop, the `vagrant-parallels` plugin upon boot detects  that the version of Parallels Tools installed in the box is outdated and tries to update it.
The problem is that a due re-compilation of Parallels Tools depends on `linux-headers-5.15.0-67-generic`, with the package name/version matching the version of the currently running kernel.
However, the Kernel version included in the box image has since then replaced with a newer version (in the upstream Ubuntu repositories), and it seems the matching header files can no longer be installed. They probably came from an Ubuntu security update release channel where the package has been replaced with a newer version …

Keep linux-kernel-header package installed for Parallels builds

---

packer_templates/scripts/windows/eject-media.ps1

Avoid downloading application to implement [eject-media.ps1](https://github.com/chef/bento/blob/main/packer_templates/scripts/windows/eject-media.ps1).
eject-media.ps1 is currently implemented using [EjectVolumeMedia](https://github.com/rgl/EjectVolumeMedia). For Windows VMs that do not have internet access at build time they will be unable to download and execute this tool. So this change implements ejecting media (Floppy disk drives and CD drives) using pure powershell.

Avoid downloading application to implement eject-media

---

packer_templates/scripts/rhel/cleanup_dnf.sh
packer_templates/scripts/rhel/cleanup_yum.sh

Bugfix for `packer build` on centos-stream-9.
The cleanup for centos-stream-9 fails during execution.
This is caused due to missing files in `/etc/sysconfig/network-scripts/ifcfg-*`.
Simple to reproduce:
`packer build -only=virtualbox-iso.vm -var-file=./os_pkrvars/centos/centos-stream-9-x86_64.pkrvars.hcl packer_templates`
```
==> virtualbox-iso.vm: + for ndev in /etc/sysconfig/network-scripts/ifcfg-*
==> virtualbox-iso.vm: ++ basename '/etc/sysconfig/network-scripts/ifcfg-*'
==> virtualbox-iso.vm: + '[' 'ifcfg-*' '!=' ifcfg-lo ']'
==> virtualbox-iso.vm: + sed -i '/^HWADDR/d' '/etc/sysconfig/network-scripts/ifcfg-*'
==> virtualbox-iso.vm: sed: can't read /etc/sysconfig/network-scripts/ifcfg-*: No such file or directory
==> virtualbox-iso.vm: Provisioning step had errors: Running the …
```

rhel: Check for networking-scripts before removal

---

packer_templates/http/ubuntu/user-data

Fix formatting error in yaml file used by netplan ... 
The problem occurs after the VM reboots and ssh connection waits (as it fails) until timeout.
Discovered this by running Netplan and reviewing the output.
```
netplan apply 
```
Whilst Building VMware Ubuntu 22.04 the build process would hang with waiting for ssh errors.
```
PACKER_LOG=1 packer build -only=vmware-iso.vm -var-file=os_pkrvars/ubuntu/ubuntu-22.04-x86_64.pkrvars.hcl -var headless=false ./packer_templates
```
The fix addresses the YAML formatting error.

Fix waiting for ssh - ubuntu netplan dhcp-identifer format error

---

packer_templates/pkr-sources.pkr.hcl

Setting `qemu_format` to `raw` in os_pkrvars directory causes wrong disk format being injected into `local.qemuargs`.
- None

Fix qemu_format="raw" causing wrong format for qemu

---

packer_templates/http/freebsd/installerconfig

Initially the problem was like
```
❯ vagrant init bento/freebsd-14.0-arm64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
❯ vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Cloning VMware VM: 'bento/freebsd-14.0-arm64'. This can take some time...
==> default: Checking if box 'bento/freebsd-14.0-arm64' version '202401.31.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding …
```

Fix a bug in freebsd-14.x due to changes in bsdinstall

---

packer_templates/scripts/_common/vmware_debian_ubuntu.sh

This pull request fixes the arm64 builds for debian 11 (bullseye).
The main problem was, that the packages `open-vm-tools` is not available for arm64 in the _bullseye_ nor the _bullseye-updates_ suite. The arm64 build is only available in the _bullseye-backports_ suite. By adding the _bullseye-backports_ suite the build succeeds.
When starting the VM a lot of _Unknown ioctl 1976_ messages are logged into kernel message log and the console. According to https://github.com/vmware/open-vm-tools/issues/495 this is because the kernel module _vmw_vsock_vmci_transport_ is missing. The kernel module is neither available in the _debian-security_ kernel (5.10.218) nor in the _bullseye-backports_ kernel (6.1.90).
The easiest fix at the moment it to blacklist the modules …

Fix arm64 builds for debian 11

---

os_pkrvars/ubuntu/ubuntu-24.04-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-24.04-x86_64.pkrvars.hcl

This change updates the ISO urls for ubuntu 24.04 to the latest URLs (modified 2024-08-29)

Update ubuntu-24.04 to latest ISO urls (24.04 to 24.04.1)

---

packer_templates/pkr-builder.pkr.hcl

With the v1.0.8 of the packer pluging hashicorp/qemu a qemu build fails with
```
Error: Unsupported argument
on packer_templates/pkr-sources.pkr.hcl line 225:
(source code not available)
An argument named "efi_drop_efivars" is not expected here.
```
v1.1.0 of the plugin fixes the build. 
See hashicorp/packer-plugin-qemu#140

update hashicorp/qemu packer plugin to fix QEMU build, supporting efi_drop_efivars variable

---

os_pkrvars/ubuntu/ubuntu-24.10-aarch64.pkrvars.hcl
os_pkrvars/ubuntu/ubuntu-24.10-x86_64.pkrvars.hcl

This PR adds support for Ubuntu 24.10 (Oracular Oriole)

add Ubuntu 24.10 (Oracular Oriole)

---

packer_templates/scripts/debian/cleanup_debian.sh
packer_templates/scripts/ubuntu/cleanup_ubuntu.sh

This PR fixes a bug in the cleanup_debian.sh and cleanup_ubuntu.sh scripts where certain dpkg | grep | xargs apt-get purge pipelines may fail if no matching packages are found.
When running on minimal images (e.g. with headers or dev packages already removed), grep returns non-zero code and causes the script to exit under set -e. Additionally, xargs without -r may invoke apt-get with no arguments, which leads to an error.
Changes:
- added '|| true' after all grep calls to avoid pipeline failures
- added xargs '-r' to skip apt-get if the input is empty
These changes are safe, maintain existing logic, and ensure the scripts work reliably in clean or partially pre-cleaned environments.

Fix: prevent cleanup script crash when no packages are found

---

packer_templates/http/debian/preseed.cfg

This PR fixes an issue in the preseed.cfg where multiple d-i preseed/late_command entries silently override each other, causing only the last one to execute.
Additionally, shell constructs like > (redirection) and && are not reliably interpreted by the installer unless explicitly passed to sh -c.
Changes:
- Combined multiple late_command lines into a single command chain
- Wrapped the full command in sh -c "..." to ensure correct shell parsing and file redirection
This ensures all late-stage installation tasks (like configuring sudo access and modifying APT sources) are executed consistently and predictably.

fix: wrap late_command in sh -c to ensure proper redirection
