- packer/scripts/sles/zypper-locks.sh
> Make script zypper-locks.sh workable

- README.md
- Relevant to issue #312
- May want to hold merge until more testing has been done
- Didn't add VMware box links, as they aren't up (see issue)
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>
> Added Fedora 21 VB base boxes to README

- packer/http/debian-7/preseed.cfg
> change mirror to http.debian.net, fixes #322

- packer/scripts/ubuntu/sudoers.sh
This PR replaces #201 and fixes an issue #302 
I have verified this changes on Ubuntu 12.04 and 14.10 as well - everything is working fine.
cc:\ @juliandunn
> Fix "sudoers.sh" for Ubuntu

- http/ubuntu-15.04/preseed.cfg
- ubuntu-15.04-amd64.json
- ubuntu-15.04-i386.json
Big thanks to @vincentaubert, @rickard-von-essen, and @YpNo for the work
in #345 and #349 to make this happen!
Closes #349
Closes #345
> Add Ubuntu 15.04 amd64/i386 templates.

- debian-8.0-amd64.json
- debian-8.0-i386.json
- http/debian-8/preseed.cfg
Big thanks to @josephholsten, @YpNo, @rickard-von-essen, @rmoriz,
@vincentaubert, and @chantra.
Closes #366
References #350
References #348
References #370
References #355
> Add Debian 8.0 amd64/i386 templates.

- http/debian-7/preseed.cfg
- http/debian-8/preseed.cfg
see:
https://lists.debian.org/debian-devel-announce/2015/05/msg00003.html
> updated debian's download redirector address

- debian-8.1-amd64.json
- debian-8.1-i386.json
Templates for #379
beware, not tested!
> preliminary debian 8.1 templates

- MAINTAINERS.md
So @cheeseplus, what do you think?
> Add @cheeseplus to MAINTAINERS.md

- Rakefile
- bin/bento
- buildkite.rb
> Box build pipeline

- bin/bento
Fixes the check for RUBY_PLATFORM
> Fixing headless check

- README.md
Adding Fedora 21 back as it passes all the kitchen tests.
> Adding Fedora 21 back to matrix

- fedora-22-i386.json
- fedora-22-x86_64.json
- http/fedora-22/ks.cfg
Note: added package ```dnf-yum``` to kickstart file to be explicit.
> Add Fedora 22 boxes

- debian-7.9-amd64.json
- debian-7.9-i386.json
> Add Debian 7.9 template

- fedora-20-i386.json
- fedora-20-x86_64.json
- fedora-21-i386.json
- fedora-21-x86_64.json
- fedora-22-i386.json
- fedora-22-x86_64.json
> [fedora-*] DRYness pass

- opensuse-13.2-i386.json
- opensuse-13.2-x86_64.json
Bringing OpenSuSE templates up to date with others
> DRY up opensuse

- Rakefile
- build.sh
First step in adding some level of automated testing to the bento build process
> Adding verification (tk) stage to build process

- fedora-20-i386.json
- fedora-21-i386.json
> Fixing templates

- scripts/common/vmtools.sh
- scripts/freebsd/vmtools.sh
- scripts/omnios/vmtools.sh
- scripts/solaris10/vmtools.sh
Fixes #283, likely several of the issues reported #377
> use --force-install for VMware tools

- build.sh
This lets us use buildkite's env variables to control whether we upload/release
> Making upload/release optional

- omnios-r151014.json
More Illumos for the Illumos Gods
> Adding OmniOS r151014

- omnios-r151014.json
- SHA changed which is not cool
> The sha changed :/

- rhel-6.7-x86_64.json
> Fix RHEL 6.7 guest type

- debian-8.3-amd64.json
- debian-8.3-i386.json
Support updated Debian 8.3 release
See https://www.debian.org/News/2016/20160123
> Add support for Debian GNU/Linux 8.3

- omnios-r151014.json
use sha1 mentioned at http://omnios.omniti.com/wiki.php/Installation
> update sha1 for omnios

- ubuntu-14.04-amd64.json
- ubuntu-14.04-i386.json
https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes/ChangeSummary/14.04.4
> Updating for 14.04.4 release

- MAINTAINERS.md
> Updating maintainers

- http/opensuse-leap-42.1/autoinst.xml
- opensuse-leap-42.1-x86_64.json
- scripts/opensuse/remove-dvd-source.sh
> Add support for OpenSUSE Leap 42.1 - x86_64

- debian-8.4-amd64.json
- debian-8.4-i386.json
Debian 8.4 has been released.
https://www.debian.org/News/2016/20160402
> Add support for Debian 8.4

- build.sh
Ran shellcheck on build.sh, replace backticks with $(), double quote strings.
> Multiple fixes to build.sh.

- freebsd-10.2-i386.json
- freebsd-10.3-amd64.json
- freebsd-10.3-i386.json
- http/freebsd-10/install.sh
- http/freebsd-9.3/install.sh
- scripts/freebsd/postinstall.sh
- scripts/freebsd/update.sh
Also move the install script for FreeBSD 10 into a major version directory
> Add FreeBSD 10.3

- debian-7.10-amd64.json
- debian-7.10-i386.json
Debian 7.10 has been released.
https://www.debian.org/News/2016/2016040202
Fixes https://github.com/chef/bento/issues/560
> Add support for Debian GNU/Linux 7.10

- README.md
- debian-8.4-amd64.json
- debian-8.4-i386.json
- ubuntu-15.10-amd64.json
- ubuntu-15.10-i386.json
> vmware: tie network device to pci slot 32, see #554

- Rakefile
will have secondary or refactored stage
> Disabling shared folder testing for now

- CHANGELOG.md
- README.md
> Readme and Changelog for 2.2.6

- scripts/common/vmtools.sh
Fixes #590 . Also improve logging for all vmtool installers.
> Set VMware script flags based on version

- scripts/ubuntu/networking.sh
> Don't disable udev rules for 15.10+

- build.sh
- want to dump env after we source .bashrc
- not just Fusion anymore :tada:
> Updating script to be a lil more informative and correct

- debian-8.5-amd64.json
- debian-8.5-i386.json
Tested on:
- VirtualBox 5.0.14
- VMware Fusion 7.1.3
- Parallels Desktop for Mac Pro ~ 11
> Updated Debian 8 to 8.5

- scripts/ubuntu/update.sh
To avoid blocking of dpkg
https://github.com/chef/bento/issues/609#issuecomment-227202607
> Disable periodic activities of apt

- scripts/common/vmtools.sh
Eventually will do this for more platforms as makes sense but as 16.04 is broken we'll start there.
> 16.04 should use open-vm-tools

- scripts/ubuntu/update.sh
Yes this in fact the fix and this was maybe always broken ¯\_(ツ)_/¯
> I regret to inform you that this is in fact the fix

- bin/bento
> Check to see if release has already taken place

- http/debian-6.0/preseed.cfg
- http/debian-7/preseed.cfg
- http/debian-8/preseed.cfg
- http/ubuntu-10.04/preseed.cfg
- http/ubuntu-12.04/preseed.cfg
- http/ubuntu-14.04/preseed.cfg
- http/ubuntu-14.10/preseed.cfg
- http/ubuntu-15.04/preseed.cfg
- http/ubuntu-15.10/preseed.cfg
Non system user should have a UID >= 1000
Closes #668
> Changed the vagrant users UID from 900 to 1000

- http/sles-12/sles-12-x86_64-autoinst.xml
- scripts/sles/remove-dvd-source.sh
Disable the firewall on SLES 12 to match SLES 12 SP1
Properly remove just the DVD source in the cleanup script
> SLES fixes

- omnios-r151014.json
- omnios-r151018.json
- solaris-11-x86.json
> Revert my vmtools change

- .travis.yml
Avoid double testing on PRs. Also test on 2.2.5 not 2.2.0
Signed-off-by: Tim Smith tsmith@chef.io
> Only build on master

- centos-5.11-x86_64.json
> CentOS 5.11-x86_64 building w/ vbox 5.1.x. Fix #729.

- scripts/centos/cleanup.sh
- scripts/fedora/cleanup.sh
- scripts/opensuse/cleanup.sh
> Provisionally keeping Perl. Redux of #714

- CHANGELOG.md
- README.md
> Prepping 2.3.1

- http/sles-12/sles-12-sp2-x86_64-autoinst.xml
- sles-12-sp2-x86_64.json
Created a new packer definition and autoyast based on the SLES 12 SP1 ones.
> Initial support for SLES 12 SP2

- scripts/centos/vmware.sh
> Fixing tab

- debian-8.7-amd64.json
- debian-8.7-i386.json
See https://lists.debian.org/debian-announce/2017/msg00000.html
> Support Debian 8.7

- Gemfile
- Rakefile
- Thorfile
- buildkite.rb
- vagrantfile_templates/freebsd.rb
- vagrantfile_templates/macosx.rb
- vagrantfile_templates/windows-nano.rb
> Chefstyle and fail if build_box not used correctly

- centos-7.3-x86_64.json
> Don't need the hack after Fusion 8.5.5

- CHANGELOG.md
- README.md
- builds.yml
> Release 2.3.4

- scripts/centos/cleanup.sh
- scripts/debian/cleanup.sh
- scripts/opensuse/cleanup.sh
- scripts/sles/cleanup.sh
> Make sure we cleanup old logs

- centos-6.9-i386.json
- centos-6.9-x86_64.json
- http/centos-6.9/ks.cfg
* Use `ks.cfg` from CentOS 6.8
> Add CentOS 6.9 boxes.

- Rakefile
- scripts/common/virtualbox.sh
> Fixing accidental revert and simplifying rakefile

- scripts/common/virtualbox.sh
> We definitely still need this for 16.04

- scripts/common/virtualbox.sh
> Adding back

- oracle-6.9-i386.json
- oracle-6.9-x86_64.json
This would be my first contribution, and I am a little confused about the "version" user vars.
> Added Oracle Linux 6.9 boxes.

- README.md
- debian-8.8-amd64.json
- debian-8.8-i386.json
> update debian to 8.8

- debian-9.0-i386.json
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
> Support Debian 9 i386

- rhel-6.9-i386.json
- rhel-6.9-x86_64.json
> Update RHEL from 6.8 to 6.9

- .travis.yml
> Update Packer version

- centos-6.9-i386.json
- centos-6.9-x86_64.json
- http/centos-6.9/ks.cfg
CentOS 6.9 building on Hyper-V for Issue #748
> Centos69 hyperv

- CHANGELOG.md
> Release 2.3.8

- http/debian-7/preseed.cfg
- http/debian-8/preseed.cfg
> Fixes #858

- centos-6.9-i386.json
- centos-6.9-x86_64.json
- centos-7.3-x86_64.json
- oracle-5.11-i386.json
- oracle-5.11-x86_64.json
- oracle-6.9-i386.json
- oracle-6.9-x86_64.json
- oracle-7.3-x86_64.json
- rhel-5.11-i386.json
- rhel-5.11-x86_64.json
- rhel-6.9-i386.json
- rhel-6.9-x86_64.json
- rhel-7.4-x86_64.json
- scripts/centos/update.sh
> Fix #639 - run  for RHELish platforms

- Rakefile
- builds.yml
> Updating rake tasks and build order

- CHANGELOG.md
> Release 201708.22.0

- rhel-5.11-i386.json
- rhel-5.11-x86_64.json
- rhel-6.9-i386.json
- rhel-6.9-x86_64.json
- rhel-7.4-x86_64.json
They won't be activated to perform updates necessarily
> Remove the update script from RHEL boxes

- http/opensuse-leap/autoinst.xml
- opensuse-leap-42.3-x86_64.json
Use a bit of config from the official opensuse packer configs
> Fix opensuse installations failing on network config

- .gitignore
- bootstrap.sh
the bento-ya gem will take care of this bit
> Moving boostrap.sh to bento-ya

- sles/sles-12-sp3-x86_64.json
> Update template for folder move

- README.md
> Adding missing cd command to readme

- centos/centos-6.9-i386.json
- centos/centos-6.9-x86_64.json
> Fixing centos template validation for hyperv

- centos/centos-7.4-x86_64.json
> CentOS 7.4

- sles/sles-12-sp3-x86_64.json
> Fixing #909

- debian/debian-9.2-amd64.json
- debian/debian-9.2-i386.json
See https://www.debian.org/News/2017/20171007
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
> Support Debian 9.2 point release

- Rakefile
> Simplifying rake tasks

- Rakefile
Templates from config now matched against file location more intelligently
> Smarter Rake

- debian/debian-9.3-amd64.json
- debian/debian-9.3-i386.json
see https://www.debian.org/News/2017/2017120902
> Support Debian 9.3 point release

- debian/debian-8.10-amd64.json
- debian/debian-8.10-i386.json
see https://www.debian.org/News/2017/20171209
> Support Debian 8.10 point release

- fedora/fedora-27-x86_64.json
Tested and working fedora-27 server build. 
Signed-off-by: Christopher P. Maher <defilan@gmail.com>
> Added fedora-27

- centos/http/7/ks.cfg
> Add cifs-utils to CentOS7 under Hyper-V

- solaris/solaris-11-x86.json
> Fixing disk in both Solari

- debian/debian-9.3-amd64.json
> Fix name for debian 9.3

- CHANGELOG.md
- Rakefile
- builds.yml
> Release 201801.02.0

- builds.yml
- oraclelinux/oracle-7.4-x86_64.json
> Update Oracle 7 to 7.4

- CHANGELOG.md
> Release 201801.05.0

- debian/http/debian-7/preseed.cfg
- debian/http/debian-8/preseed.cfg
> Using more reliable debian mirror

- ubuntu/scripts/cleanup.sh
> Exclude firmware files w/o removing linux-firmware

- CHANGELOG.md
> Release 201802.02.0

- debian/http/debian-7/preseed.cfg
- debian/http/debian-8/preseed.cfg
- ubuntu/http/preseed-hyperv.cfg
- ubuntu/http/preseed.cfg
> Add cifs-utils for debian/ubuntu

- freebsd/freebsd-10.3-amd64.json
- freebsd/freebsd-10.3-i386.json
- freebsd/freebsd-10.4-amd64.json
- freebsd/freebsd-10.4-i386.json
- freebsd/freebsd-11.1-amd64.json
- freebsd/freebsd-11.1-i386.json
- freebsd/scripts/postinstall.sh
- freebsd/scripts/update.sh
- freebsd/scripts/vmtools.sh
along with some pkg related cleanups
> FreeBSD: Add new variable pkg_branch for choosing pkg branch

- debian/debian-9.4-amd64.json
- debian/debian-9.4-i386.json
ref. https://www.debian.org/News/2018/20180310
> Support Debian 9.4

- builds.yml
- fedora/fedora-28-x86_64.json
> Fix Fedora 28 name and add to builds

- oraclelinux/oracle-7.5-x86_64.json
> Update for Oracle Linux 7.5

- scientificlinux/SL-7-x86_64.json
- scientificlinux/http/7/ks.cfg
- scientificlinux/scripts/cleanup.sh
- scientificlinux/scripts/networking.sh
- scientificlinux/scripts/update.sh
(seperate PR) 
https://www.scientificlinux.org/
> Scientific Linux packer built vagrant box 

- windows/2008r2.json
- windows/2012r2.json
- windows/2016.json
- windows/7.json
- windows/cookbooks/packer/kitchen.yml
- windows/cookbooks/packer/recipes/cleanup.rb
- windows/cookbooks/packer/recipes/features.rb
- windows/cookbooks/packer/recipes/uninstall_powershell_ise.rb
- windows/cookbooks/packer/recipes/updates.rb
- windows/scripts/cleanup.ps1
Install .NET 3.5
Cleanup the old Chef directories when we're done
Cleanup the Event Log
Disable Windows Update downloads
Install the 2018-05 monthly update package which is 200+ megs of bug fixes
> Improvements for Windows 2008 R2

- debian/debian-8.11-amd64.json
- debian/debian-8.11-i386.json
See https://www.debian.org/News/2018/20180623
> Support Debian 8.11

- .travis.yml
> Test on Ruby 2.5

- scientificlinux/SL-7.5-x86_64.json
> Use a faster scientific mirror

- .travis.yml
> Test with the latest packer

- CHANGELOG.md
> Adding missing changelog entries

- ubuntu/http/preseed-hyperv.cfg
- ubuntu/http/preseed.cfg
> Ubuntu: add back software-properties-common

- CHANGELOG.md
> Release v201807.12.0

- CHANGELOG.md
- README.md
> Release v201808.24.0

- fedora/fedora-29-x86_64.json
- fedora/http/ks-fedora29.cfg
> Add Fedora 29 support.

- windows/2008r2.json
- windows/2012r2.json
- windows/2016.json
- windows/7.json
- windows/cookbooks/packer/recipes/disable_uac.rb
- windows/cookbooks/packer/recipes/enable_remote_desktop.rb
We wanted UAC to be disabled on these boxes. We also want to use native chef resources where possible.
> Make sure to disable UAC on windows

- debian/debian-9.6-amd64.json
- debian/debian-9.6-i386.json
> Debian 9.6

- builds.yml
- freebsd/freebsd-11.2-i386.json
based on similar fix for the am64 box in #1103 cc @cheeseplus 
attempts to fix #1135
> Fix build/upload of freebsd-11.2-i386

- oraclelinux/oracle-7.6-x86_64.json
> Update Oracle Linux 7.5 -> 7.6

- .expeditor/config.yml
This will start notifying on merges and it'll clean up branches.
> Add a basically empty expeditor config

- .travis.yml
Update to the latest versions in Travis
> Update Travis to use Ruby 2.5.3 and Packer 1.3.2

- _common/minimize.sh
Whiteout all spaces to reduce box size
> Whiteout all spaces

- centos/http/5/ks.cfg
- centos/http/6/ks.cfg
- centos/http/7/ks.cfg
Only one language (en_US.utf8) will be installed. This will reduce the box size ~> 50 mb
> Reduce centos locale size

- centos/centos-7.6-x86_64.json
> CentOS 7.6

- builds.yml
- freebsd/freebsd-12.0-amd64.json
- freebsd/freebsd-12.0-i386.json
Add configurations for FreeBSD 12.0-RELEASE
> Add FreeBSD 12.0-RELEASE

- builds.yml
- centos/centos-7.6-x86_64.json
Fix 7.6 template name field and add to build/slug list
> Fix CentOS 7.6 name field and add to builds

- CHANGELOG.md
Signed-off-by: Seth Thomas <seth.g.thomas@gmail.com>
Fix #1164
> Adding changelog for 201812.27.0 release

- windows/2019.json
- windows/answer_files/2019/Autounattend.xml
It could be tweaked further, but it works.
> Initial Windows 2019 definition

- windows/cookbooks/packer/recipes/updates.rb
> Update to a newer monthly rollup for Windows 2008 R2

- windows/2016.json
- windows/2019.json
- windows/cookbooks/packer/recipes/disable_uac.rb
- windows/cookbooks/packer/recipes/enable_remote_desktop.rb
> Fully disable UAC

- .travis.yml
- Rakefile
We should know we have the correct format on merge
> Add template validation in Travis

- amazon/STEP1_build_ovf.sh
- amazon/amazon-2-x86_64.json
- amazon/seed_iso/user-data
Pushes forward on the Amazon Linux 2 box.
Continues where https://github.com/chef/bento/pull/1144 left off.
> Amazon Linux 2

- .gitignore
- amazon/STEP1_build_ovf.sh
- amazon/amazon-2-x86_64.json
- amazon/scripts/cleanup.sh
- amazon/scripts/networking.sh
- amazon/scripts/update.sh
- amazon/seed_iso/meta-data
- amazon/seed_iso/user-data
Amazon provides a disk image and expects you to create an ISO with cloud-init files, which will be read when the disk boots. This automates creating the ISO, creating the VM from the disk image and exporting the OVF file. Next step is consuming that file in a packer template and then we have a vagrant box.
> Amazon Linux 2 definition

- sles/http/sles-15-x86_64-autoinst.xml
- sles/sles-15.json
Added sles-15.json config for building SLES-15 images
> Added support for SLES 15

- README.md
[Please describe what this change achieves]
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]
> Update requirements for Parallels builds

- .expeditor/config.yml
This has to get merged before we can actually drop the real tests
> Wire up Expeditor to handle PR testing with Buildkite

- packer_templates/windows/cookbooks/packer/kitchen.yml
- packer_templates/windows/cookbooks/packer/recipes/disable_windows_defender.rb
Signed-off-by: Joe Ferguson <joe@joeferguson.me>
Disables Windows Defender so provisioning should be faster
Resolves #1171
> Disable Windows Defender

- packer_templates/sles/http/sles-15-sp1-x86_64-autoinst.xml
- packer_templates/sles/scripts/remove-dvd-source.sh
- packer_templates/sles/sles-15-sp1.json
- Initial commit of a config that builds SLES 15 SP1.
- Reduce footprint of resulting image.
- Add bzip2/tar packages in order to support the installation of
VirtualBox Additions
- Misc fixes in post scripts
Signed-off-by: Mattias Giese <mattiasgiese@posteo.net>
This commit adds a recipe to build SLES 15 SP1
>  Introduce SLES 15 SP1

- builds.yml
- packer_templates/centos/centos-8.0-x86_64.json
- packer_templates/centos/http/8/ks.cfg
Adding a package for Centos 8 to be able to use test-kitchen with the new release. This commit was made from the github web UI so most of the checklist can't be done.
None
> Adding a package for Centos 8

- packer_templates/centos/http/8/ks.cfg
- packer_templates/centos/scripts/cleanup.sh
- packer_templates/centos/scripts/networking.sh
- packer_templates/rhel/rhel-8.0-x86_64.json
Adding RHEL 8 support along with some minor fixes for cleanup and network scripts.
Signed-off-by: Christopher A. Snapp <csnapp@chef.io>
> add rhel 8 support

- builds.yml
- packer_templates/freebsd/freebsd-12.1-amd64.json
- packer_templates/freebsd/freebsd-12.1-i386.json
Add FreeBSD-12.1 templates.
I've tested with these commands and tested in vagrant:
```
packer build -only=virtualbox-iso freebsd-12.1-amd64.json
packer build -only=virtualbox-iso freebsd-12.1-i386.json
```
> Add FreeBSD-12.1 definitions

- packer_templates/_common/minimize.sh
> Revert "Incorrect calculation of block count"

- packer_templates/windows/answer_files/2012/Autounattend.xml
- packer_templates/windows/windows-2012.json
Add new template for Windows Server 2012.
Template and answer file are copied from Windows Server 2012 R2 with minimal changes.
> Add support for Windows Server 2012

- packer_templates/freebsd/freebsd-11.3-i386.json
Fix dhclient parameter for freebsd-11.3-i386.json
> Fix dhclient paramater

- builds.yml
- packer_templates/freebsd/freebsd-11.4-amd64.json
- packer_templates/freebsd/freebsd-11.4-i386.json
> Add FreeBSD 11.4-RELEASE

- packer_templates/freebsd/scripts/postinstall.sh
- packer_templates/freebsd/scripts/vmtools.sh
Make FreeBSD boot very slightly faster.
> FreeBSD faster boot

- .expeditor/verify.pipeline.yml
> Test on Packer 1.6.0 not 1.4.2

- builds.yml
- packer_templates/freebsd/freebsd-12.2-amd64.json
- packer_templates/freebsd/freebsd-12.2-i386.json
Add FreeBSD 12.2-RELEASE definitions, which is released on 2020-10-27.
> Add FreeBSD 12.2-RELEASE

- packer_templates/fedora/fedora-33-x86_64.json
Add Fedora 33
Add Fedora 33 released in october 2020
> Add Fedora 33

- builds.yml
- packer_templates/centos/centos-stream-8-x86_64.json
- packer_templates/centos/http/8-stream/ks.cfg
Signed-off-by: Lance Albertson <lance@osuosl.org>
> Add CentOS Stream 8 config

- packer_templates/freebsd/freebsd-13.0-amd64.json
> Add FreeBSD 13.0-RELEASE

- packer_templates/debian/http/debian-9/preseed.cfg
- packer_templates/ubuntu/http/preseed-hyperv.cfg
- packer_templates/ubuntu/http/preseed.cfg
A couple of the preseed files had duplicate lines. I removed the duplicates.
> Remove Duplicate Lines From Preseeds

- builds.yml
- packer_templates/freebsd/freebsd-12.3-amd64.json
Add [FreeBSD-12.3-RELEASE](https://app.vagrantup.com/freebsd/boxes/FreeBSD-12.3-RELEASE), which was released almost a fortnight ago.  The structure of this PR follows #1319.
> feat(freebsd): add FreeBSD 12.3

- packer_templates/freebsd/freebsd-13.1-amd64.json
> Add FreeBSD 13.1-RELEASE

- packer_templates/fedora/fedora-36-arm64.json
Signed-off-by: Wil Taylor <wil.taylor@socotra.com>
> add fedora 36 arm64 parallels packer template

- packer_templates/fedora/fedora-37-x86_64.json
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the
best of my knowledge, is covered under an appropriate open
source license and I have the right under that license to
submit that work with modifications, whether created in whole
or in part by me, under the same open source license (unless
I am permitted to submit under a different license), as
Indicated in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this project and the contribution
are public and …
> remove Fedora 35 (end of support), add Fedora 37

- builds.yml
- packer_templates/rockylinux/rockylinux-8.7-x86_64.json
Signed-off-by: Benjamin Bertrand <beenje@gmail.com>
Update rockylinux box from 8.6 to 8.7
> Bump rockylinux to 8.7

- packer_templates/almalinux/almalinux-9.0-x86_64.json
> remove network script to fix errors - this isn't needed.

- builds.yml
- packer_templates/opensuse/opensuse-leap-15.4-x86_64.json
> Update opensuse 15.3 -> 15.4

- packer_templates/_common/vagrant.sh
> Update the URL for the vagrant key

- builds.yml
- packer_templates/almalinux/almalinux-8.7-aarch64.json
- packer_templates/almalinux/almalinux-8.7-x86_64.json
- packer_templates/almalinux/almalinux-9.1-aarch64.json
- packer_templates/almalinux/almalinux-9.1-x86_64.json
Also try tossing in another arm config.
Signed-off-by: Tim Smith <tsmith84@gmail.com>
> Bump AlmaLinux 9.0 -> 9.1 and 8.6 -> 8.7

- .github/CODEOWNERS
- .github/workflows/ci.yml
- .github/workflows/packer-builds.yml
- CHANGELOG.md
> Update changelog for release

- os_pkrvars/fedora/fedora-36-aarch64.pkrvars.hcl
Fix arch for fedora 36 aarch64
> Fix arch for fedora 36 aarch64

- .github/workflows/pkr-bld-amazonlinux-x64.yml
- .github/workflows/pkr-bld-hyperv-x64.yml
- .github/workflows/pkr-bld-parallels-x64.yml
- .github/workflows/pkr-bld-qemu-x64.yml
- .github/workflows/pkr-bld-virtualbox-x64.yml
- .github/workflows/pkr-bld-vmware-x64.yml
- AMZ_build_virtualbox-ovf.sh
- CHANGELOG.md
- os_pkrvars/debian/debian-12-aarch64.pkrvars.hcl
Remove packer setup from pipeline and rely on home brew installed packer.
> fix pipeline

- os_pkrvars/freebsd/freebsd-13-aarch64.pkrvars.hcl
> Fix os_arch of freebsd-13-aarch64 config

- packer_templates/http/ubuntu/user-data
> fix shell exec err

- .github/workflows/pkr-bld-hyperv-x64.yml
- .github/workflows/pkr-bld-parallels-arm64.yml
- .github/workflows/pkr-bld-parallels-x64.yml
- .github/workflows/pkr-bld-qemu-arm64.yml
- .github/workflows/pkr-bld-qemu-x64.yml
- .github/workflows/pkr-bld-virtualbox-arm64.yml
- .github/workflows/pkr-bld-virtualbox-x64.yml
- .github/workflows/pkr-bld-vmware-arm64.yml
- .github/workflows/pkr-bld-vmware-x64.yml
- .github/workflows/test-pkr-bld-parallels.yml
- builds.yml
- os_pkrvars/fedora/fedora-42-aarch64.pkrvars.hcl
- os_pkrvars/fedora/fedora-42-x86_64.pkrvars.hcl
> feat(fedora): add Fedora 42

- .github/workflows/pkr-bld-amazonlinux-arm64.yml
- .github/workflows/pkr-bld-amazonlinux-x64.yml
- .github/workflows/pkr-bld-hyperv-x64.yml
- .github/workflows/pkr-bld-qemu-x64.yml
- .github/workflows/pkr-bld-virtualbox-x64.yml
- .github/workflows/test-pkr-bld-parallels.yml
- os_pkrvars/macos/macos-15-aarch64.pkrvars.hcl
- packer_templates/pkr-builder.pkr.hcl
- packer_templates/scripts/_common/build_tools.sh
- packer_templates/scripts/_common/guest_tools_parallels.sh
- packer_templates/scripts/_common/guest_tools_virtualbox.sh
- packer_templates/scripts/_common/guest_tools_vmware.sh
- packer_templates/scripts/_common/update_packages.sh
- packer_templates/scripts/_common/vagrant.sh
use universal shutdown command vs reboot command.
> update common scripts reboot command

- packer_templates/scripts/_common/guest_tools_parallels.sh
- packer_templates/scripts/_common/guest_tools_virtualbox.sh
- packer_templates/scripts/_common/guest_tools_vmware.sh
fix HOME_DIR and OS_NAME order in common scripts
> fix HOME_DIR and OS_NAME order in common scripts
